### ISSUE TITLE
bodhi update with no packages, now cannot edit at all

### ISSUE THREAD

**Issue by rdieter** [fedora-infra/bodhi#234] opened 2015-08-20 12:50 UTC
I tried to edit an update by removing one build and adding another... and somehow ended up with an update with 0 packages in it.  It's currently item 2 in list displayed in 'rdieter's latest updates' on
https://bodhi.fedoraproject.org/users/rdieter
between
konsole5-15.04.3-2.fc23
and
(now) konsole5-15.04.3-2.fc22.1

The update I tried editing originally had konsole5-15.04.3-2.fc22

**Comment by rdieter** [comment] 2015-08-20 12:52
Here's a screenshot of the "empty" update listed if that helps,
https://rdieter.fedorapeople.org/bodhi2.png

**Comment by lmacken** [comment] 2015-08-20 13:19
Duplicate of #202.

Did you press enter after adding the build nvr to the Candidate builds text field, and then check the box next to it once it appeared below? People seem to be getting confused about that interface, and it really needs to properly error out, as opposed to wiping out all of builds.

**Closed by lmacken** 2015-08-20 13:19 UTC
