### ISSUE TITLE
Show `koji --profile stg` in override?

### ISSUE THREAD

**Issue by tkdchen** [fedora-infra/bodhi#2384] opened 2018-05-23 06:49 UTC
I created an override[1] in bodhi.stg. In this screenshot, should the `wait-repo` command work against Koji stage? Or does bodhi.stg just work with Koji prod?

![screenshot-2018-5-23 fedora updates system](https://user-images.githubusercontent.com/919706/40407789-28661184-5e98-11e8-84d7-bcdbdc8db56d.png)

[1] https://bodhi.stg.fedoraproject.org/overrides/rpkg-1.54-2.fc26

**Comment by tkdchen** [comment] 2018-05-26 02:34
@bowlofeggs Could you give me some guidance and hint where the problem happens inside Bodhi? I'm willing to help.

**Comment by bowlofeggs** [comment] 2018-05-29 20:08
Hello @tkdchen!

Fixing this would be kind of complex and may not be worth the effort in my opinion. The problem is that Bodhi's server doesn't have a concept of staging vs. production, and even further Fedora's Bodhi is not the only Bodhi deployment in the wild. I think this problem would affect few users, so I personally would recommend not worrying about it.

That said, if you do want to pursue it, you could add a new setting to Bodhi's ```production.ini``` to allow deployment-specific Koji commands to be displayed. What gets even more complicated is that the CLI also gives these instructions and does so in its own way, so it would be even more work/complexity to fix that too. If you want to take it on I'm not opposed, but I suggest that it may not be the best use of time since staging has so few users.

**Comment by tkdchen** [comment] 2018-05-31 04:56
@bowlofeggs Got it. Thanks for your explanation and suggestion.

**Comment by bowlofeggs** [comment] 2019-04-30 21:47
@tkdchen do you want to fix this, and/or keep it open? Or shall we close it?

**Comment by tkdchen** [comment] 2019-05-28 09:01
@bowlofeggs I'm afraid I don't have enough time to fix it now, although I'm really willing to hack on Bodhi code. I'm not sure how many people are impacted by this issue, but it seems this is not a big problem as it happens in stg after all. Feel free to close it. If someone else is going to make a patch, it is appreciated. :)

**Closed as completed** 2019-05-29 17:06 UTC
Labels: Low Priority, Client, Buildroot Override, WebUI
