### ISSUE TITLE
New update page keeps loading on submit, creates only 1 update

### ISSUE THREAD

**Issue by hroncok** [fedora-infra/bodhi#3927] opened 2020-02-12 15:05 UTC
I have noticed recently that the https://bodhi.fedoraproject.org/updates/new page just keeps "loading" in the Submit button forever, while it actually creates the update.

More importantly, on multi-target updates like this one:

![_](https://user-images.githubusercontent.com/2401856/74347429-5fcc5c00-4db1-11ea-8fed-e3f752f0e348.png)

...it only creates one of them (in this case the latter).

**Comment by mattiaverga** [comment] 2020-02-13 17:49
Closing as duplicate of #3918

**Closed as completed by mattiaverga** 2020-02-13 17:49 UTC
