### ISSUE TITLE
Can't create new update for fc24 build

### ISSUE THREAD

**Issue by terminalmage** [fedora-infra/bodhi#790] opened 2016-03-01 17:52 UTC
[This build](http://koji.fedoraproject.org/koji/buildinfo?buildID=740519) cannot be found by bodhi when attempting to create a new update:

```
% fedpkg update
/usr/lib/python2.7/site-packages/fedpkg/cli.py:169: DeprecationWarning: Commands._hash_file is deprecated and will be removed eventually.
    Please use Commands.lookasidecache.hash_file instead.
  hash = self.cmd._hash_file('bodhi.template', 'sha1')
No handlers could be found for logger "fedora.client.bodhi"
Creating a new update for  salt-2015.5.9-5.fc24
Traceback (most recent call last):
  File "/bin/bodhi", line 532, in <module>
    main()
  File "/bin/bodhi", line 225, in main
    data = bodhi.save(**update_args)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 104, in wrapper
    raise BodhiClientException(problems)
fedora.client.bodhi.BodhiClientException: Invalid tag: salt-2015.5.9-5.fc24 tagged with [u'epel7-testing-candidate', u'dist-6E-epel-testing-candidate', u'dist-5E-epel-t
esting-candidate', u'f22-updates-candidate', u'f23-updates-candidate', u'f21-updates-candidate']
Unable to determine release from build: salt-2015.5.9-5.fc24
Could not generate update request: Command 'bodhi --new --release f24 --file bodhi.template salt-2015.5.9-5.fc24 --username terminalmage' returned non-zero exit status
1
```

**Comment by lmacken** [comment] 2016-03-01 18:26
F24 is not currently enable in bodhi, and your build got tagged into `f24` directly.

We should, however, make this error a little more clear, since I'm sure a number of people have tried to do this as well.

**Comment by terminalmage** [comment] 2016-03-01 18:31
OK, are f24 builds going directly into the repo then, similar to epel7 early on?

**Comment by terminalmage** [comment] 2016-03-01 18:32
I would assume so, if they're being tagged directly into f24.

**Comment by lmacken** [comment] 2016-03-01 19:33
Yep, that's correct, until we reach alpha I believe.

**Comment by terminalmage** [comment] 2016-03-01 20:04
OK, thanks for confirming.

**Comment by ryanlerch** [comment] 2017-08-03 02:41
The error message here should be re-worked, as in this example, the user is trying to submit an update to rawhide.

There is an open bug already to improve this messaging for submitting against rawhide, so closing this one as a duplicate of #611

**Closed by ryanlerch** 2017-08-03 02:41 UTC
