### ISSUE TITLE
Do not show updates from unsupported Fedora versions in users' profile pages

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#963] opened 2016-09-22 18:56 UTC
jskarvad reported that Bodhi is displaying updates for Fedora versions that are no longer supported on his user profile. In his case, these are Fedora 21 updates that were never pushed to stable, and Fedora 21 went end of life many months ago. He requests that Bodhi not display updates for non-supported Fedora releases in user profiles, which I think is reasonable.

This was originally reported in [Fedora Infrastructure Trac ticket #5489](https://fedorahosted.org/fedora-infrastructure/ticket/5489).

**Comment by ryanlerch** [comment] 2017-08-02 13:06
Closing this one as a duplicate of #752

**Closed as completed by ryanlerch** 2017-08-02 13:06 UTC
Labels: RFE, WebUI
