### ISSUE TITLE
Make sure bodhi always tags the latest NVR to the appropriate repo

### ISSUE THREAD

**Issue by nullr0ute** [fedora-infra/bodhi#363] opened 2015-08-25 13:38 UTC
There's been an issue for some time in bodhi1 which was know where it would tag an older NVR over the newer one, it was one of the "we'll fix this in bodhi2". Not sure if the issue listed is a left over from the v1 or whether it still needs to be addressed

https://lists.fedoraproject.org/pipermail/devel/2015-August/213803.html

$ koji list-history --tag=f21-updates-testing --package=python-fedora
Thu Aug 20 21:58:35 2015 python-fedora-0.5.5-1.fc21 tagged into f21-updates-testing by bodhi [still active]
Sat Aug 22 00:02:51 2015 python-fedora-0.5.4-1.fc21 tagged into f21-updates-testing by bodhi [still active]

**Comment by lmacken** [comment] 2015-08-25 14:34
Bodhi1 would tag things out of order when multiple builds for the same update were in the same push. There was code written to order the builds properly before tagging, but unfortunately with koji multicalls we are not guaranteed order of execution.

In this case, the updates were pushed days a part. So, I think both of these scenarios need to be accounted for

**Comment by ralphbean** [comment] 2015-08-27 15:23
**Idea** we should add logic to the *sanity check* phase of the mash that checks for builds of the same package in the mash.  The older versions should be *ejected* before we proceed.

Bodhi2 (like @lmacken mentioned) already orders things properly, but then hands things off to a koji multicall, which does things out of order.  Let's eject those old bits before we get into koji multicall land.

**Comment by nullr0ute** [comment] 2015-08-27 15:58
Or possibly apply a basic sort routine to ensure tagging order?

**Comment by ralphbean** [comment] 2015-08-27 16:24
@nullr0ute so, it already does that.  Then it hands that sorted list to a koji multicall which (we think) handles things out of order.

**Comment by lmacken** [comment] 2015-09-02 22:18
This is a duplicate of #94

**Closed by lmacken** 2015-09-02 22:18 UTC
Labels: Critical, Masher
