### ISSUE TITLE
RFE: Add way to revoke update for archived release or cancel them automatically after some time

### ISSUE THREAD

**Issue by zdohnal** [fedora-infra/bodhi#1802] opened 2017-09-13 06:43 UTC
Hi,

when I use CLI interface to list my updates, which are in pending/testing phase, I got listed even updates, which are for archived release and I cannot revoke or cancel them. Would you mind adding any means to deal with them?

**Comment by bowlofeggs** [comment] 2017-09-13 22:20
Hello, and thanks for reporting!

I believe this is a duplicate of https://github.com/fedora-infra/bodhi/issues/752, especially given my proposed fix.

**Closed as completed by bowlofeggs** 2017-09-13 22:20 UTC

**Comment by zdohnal** [comment] 2017-09-14 06:21
Yes, you're right, that's totally what I would want. Sorry for duplicate, I missed that one.
