### ISSUE TITLE
Cannot edit updates using the Bodhi CLI

### ISSUE THREAD

**Issue by kkofler** [fedora-infra/bodhi#1125] opened 2016-11-22 01:01 UTC
I tried working around #1033 by using the CLI instead:
```
bodhi -u kkofler -e --disable-autokarma -S 1 calamares-2.4.4-5.fc25
```
but that does not work either. (Using bodhi-client-0.9.12.2-4.fc24.noarch, the latest in F24 stable.)

I get
```
fedora.client.bodhi.BodhiClientException: type is missing
Required
Update for calamares-2.4.4-5.fc25 already exists
Invalid tag: calamares-2.4.4-5.fc25 not tagged with any of the following tags [u'f22-updates-candidate', u'dist-6E-epel-testing-candidate', u'dist-5E-epel-testing-candidate', u'f21-updates-candidate', u'f24-updates-candidate', u'f23-updates-candidate', u'epel7-testing-candidate', u'f25-updates-candidate']
```
and even if I pass `-t security` to work around the "type is missing", I still get the remaining 3 errors.

The comment for the `save` method in `bodhi.py` says:
```
        To edit an existing update, you must specify the update title in
        the ``edited`` keyword argument.
```
but `/usr/bin/bodhi` passes:
```
                data = bodhi.save(builds=args[0], type_=opts.type_,
                                  bugs=opts.bugs, notes=opts.notes,
                                  request=opts.request)
```
instead.

The combination of #1033 and this bug is preventing me from pushing security updates in a timely manner. Why is it taking so long to fix such critical showstoppers?

**Comment by kkofler** [comment] 2016-11-22 01:27
Whatever I do, I cannot get the CLI or even the Python API to work for editing, it keeps wanting stuff that I don't want changed (at least build, type, notes), it seems like I would have to query for them and them manually translate them to what it expects. I naïvely tried:
```python
u = dict(bodhi.query(updateid='FEDORA-2016-561a937494')[u"updates"][0])
del u[u"comments"]
u[u"edited"]=u'FEDORA-2016-561a937494'
u[u"stable_karma"]=1
bodhi.save(**u)
```
but it complains that the builds are in the wrong format.

So neither the web UI nor the CLI are able to perform such a simple edit correctly.

**Comment by kkofler** [comment] 2016-11-22 01:29
(I need to push calamares-2.4.4-5.fc25 and calamares-2.4.4-5.fc24 that both have a karma of +1.)

**Comment by kkofler** [comment] 2016-11-24 16:25
I see that there is a new client:
https://github.com/fedora-infra/bodhi/blob/develop/bodhi/client/__init__.py
which is only in Rawhide/Copr and not actually in the repositories, but that does not even have an edit command at all anymore.

**Comment by bowlofeggs** [comment] 2017-02-17 21:44
@cverna noted that this report is a duplicate of #937.

**Closed as completed by bowlofeggs** 2017-02-17 21:44 UTC
Labels: RFE, Client, High priority
