### ISSUE TITLE
Disabling autokarma (still) removes the karma thresholds

### ISSUE THREAD

**Issue by kkofler** [fedora-infra/bodhi#1033] opened 2016-10-14 23:48 UTC
Whenever I edit an update to disable autokarma (I have to edit it, as opposed to just unchecking the box from the beginning, due to issue #1032), the thresholds vanish. The only way to get the thresholds back is to enable autokarma. As a result, the improvement from issue #772 (manual push to stable based on karma) does not work: if I disable autokarma, it does not work because the thresholds are deleted (which is clearly a bug); if I enable autokarma, it does not work because the button explicitly gets disabled if autokarma is enabled for some reason. (Why? It can be valid to trigger a manual push based on karma even if autokarma is enabled, because, if the update already had a karma of +1 and I set the autokarma threshold to +1, the automatic push will not trigger.)

**Comment by bowlofeggs** [comment] 2016-10-15 15:16
I believe this is likely a UI issue, in either form rendering or processing (or both). As a workaround, I believe the CLI can be used to do this.

**Comment by kkofler** [comment] 2016-11-22 01:31
It's in the processing, not in the rendering. I did the query using the Python API, it clearly shows that stable_karma=None on the updates I disabled autokarma for using the web UI, so it was already incorrectly saved.

**Comment by kkofler** [comment] 2016-11-22 01:33
And no, the CLI can NOT be used for this, see #1125.

**Comment by kkofler** [comment] 2016-12-30 01:34
2 months and this showstopper is STILL not fixed.

**Comment by kkofler** [comment] 2016-12-30 01:42
Counting also #772, it has been almost 11 months that manual push to stable based on karma has no longer worked. Why is it taking so long to fix such a major issue? This is breaking the best-practice workflow for filing Fedora updates and encouraging people to just enable autokarma, with all the issues this entails (broken upgrade paths, updates being pushed after gaining karma too quickly with negative feedback either coming too late or being outvoted, etc.).

**Comment by bowlofeggs** [comment] 2017-03-15 16:05
I found the cause of this bug:

https://github.com/fedora-infra/bodhi/blob/2.4.0/bodhi/server/models/models.py#L897-L898

I think we can just drop those two lines of code, write a test, and it will be fixed.

**Comment by trishnaguha** [comment] 2017-03-16 10:52
@dustymabe has also confirmed this issue. I am working on the fix.

**Closed as completed** 2017-03-16 17:45 UTC
Labels: High priority
