### ISSUE TITLE
bodhi seems to have problems with the new Firefox package

### ISSUE THREAD

**Issue by JayJayJazz** [fedora-infra/bodhi#968] opened 2016-09-23 12:53 UTC
The new Firefox 49.0 package is not pushed to stable, even it has already +13 Karma.

Link:
https://bodhi.fedoraproject.org/updates/FEDORA-2016-a6672dbd40

It is also quite strange that bodhi just adds empty comments.
Can someone please have a look?

**Comment by bowlofeggs** [comment] 2016-09-23 13:52
I believe this is a duplicate of https://github.com/fedora-infra/bodhi/issues/950

Thanks for the report!

**Closed as completed by bowlofeggs** 2016-09-23 13:52 UTC
