### ISSUE TITLE
Option to manually create update title is too prominent, encourages people to create useless titles

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#3809] opened 2019-11-27 17:28 UTC
Since the recent Bodhi update overhaul, the option to manually specify the update title is very prominent in the update creation UI, and it's not very obvious that you can just leave it blank and get an autogenerated title.

This is causing lots of people to create updates with useless titles, like https://bodhi.fedoraproject.org/updates/FEDORA-2019-edc1551b22 for e.g. where the title is just the package name (but no version or release). I am yet to see a manually created title that would actually be better than the autogenerated title.

Can we change this UI again to de-emphasize manual title creation, since it's so rarely a good idea?

**Comment by jamesjer** [comment] 2019-11-27 20:45
Yes, please don't make it the first thing people see.  On my first interaction with the UI, I expected that field to be the same as the previous top field, the one that lets you search for a package name.  Move the title field way, way down, please, and put the search box back on top.  That's the first field I want to type in.

**Comment by ryanlerch** [comment] 2019-11-28 04:13
Duplicate of issue #3640 

Note to that this is also fixed in develop with PR #3705 and will be pushed to prod in the next bodhi release.

**Closed as completed by ryanlerch** 2019-11-28 04:13 UTC
