### ISSUE TITLE
bodhi sends endless spam if two Rawhide packages are built at the same time and the lower NVR one finishes second

### ISSUE THREAD

**Issue by rwmjones** [fedora-infra/bodhi#3831] opened 2019-12-05 11:50 UTC
The situation is that I had started the build of `nbdkit-1.17.1-2.fc32` and forgotten about it.  A new upstream release of nbdkit happened about the same time so I then started a build of `nbdkit-1.17.2-1.fc32`.

The second (higher NVR) build finished first.

The first (lower NVR) build finished second.  This resulted in the following Rawhide update being automatically generated:

https://bodhi.fedoraproject.org/updates/FEDORA-2019-d9458cbc80

However this update then ended up "stuck" in some way.  It sent me spam every few minutes about `This update cannot be pushed to stable. These builds nbdkit-1.17.1-2.fc32 have
a more recent build in koji's f32 tag`.  See example here: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/ABRNJT5YPYN2ZM2MB2S2Z3TTF557PYOE/

The spam stopped after about 24 hours for unknown reasons, although in that time I received about 300 messages.  However the update still exists.

Also there is no way to delete or obsolete updates from the UI.

**Comment by cverna** [comment] 2019-12-05 14:54
This was caused by #3828 with was hot fixed in production. I also have obsoleted the update from the database.
So that should be not be a problem any more. 

Sorry about all these email :mailbox_closed:

**Closed as completed by cverna** 2019-12-05 14:54 UTC
