### ISSUE TITLE
Can not push update to stable, even though there is a comment that I can

### ISSUE THREAD

**Issue by thozza** [fedora-infra/bodhi#2133] opened 2018-01-22 15:22 UTC
https://bodhi.fedoraproject.org/updates/dnssec-trigger-0.15-1.fc27#comment-710350 contains a comment "This update has reached 7 days in testing and can be pushed to stable now if the maintainer wishes". However there is no "push to stable" button...

I tried using CLI "bodhi updates request FEDORA-2017-6fdbb08336 stable" however it failed with "This update has not yet met the minimum testing requirements defined in the <a href="https://fedoraproject.org/wiki/Package_update_acceptance_criteria">Package Update Acceptance Criteria</a>". However I'm not able to figure out which requirements are not met. The test results for the update can not be found, but I expect this is a problem on the Bodhi side...

**Comment by remicollet** [comment] 2018-01-23 05:27
Same issue with 
* https://bodhi.fedoraproject.org/updates/FEDORA-2018-edbc70d0df
* https://bodhi.fedoraproject.org/updates/FEDORA-2018-de41d0571b

**Comment by thozza** [comment] 2018-01-23 09:56
While Remi's tests failed, my situation is "no test results found". I'm not sure shat to do with that....

**Comment by AdamWill** [comment] 2018-01-23 17:00
It seems like the Taskotron tests for this package really did not run, as there are just no automated test results for it at all. I am not sure what would cause that. Let's tag...

@tflink @rajcze

I think Bodhi and Greenwave are more or less doing 'the right thing' here, as the basic rule is 'the tests must have passed': if they weren't run, they haven't passed. But obviously it's not viable if they're not always getting run when they should be...

**Comment by AdamWill** [comment] 2018-01-23 22:23
So, after some real world discussion, it seems there are quite a few known cases where Taskotron tasks for some package just...didn't get run, for various reasons. This has always happened and never been a high priority to fix because it hasn't previously caused any major problems.

Of course, now we have a gating policy that effectively assumes that certain tests will *always* be run, it *does* cause significant problems, and we're gonna have to do something about that in the short term. Just turning off the gating again would be the easiest thing, of course. The other suggestion we're kicking around is to invert the policy, so that an update is only blocked if one of the 'required' tests *definitely failed*, rather than always being blocked until all the 'required' tests *definitely passed*. This is obviously a looser policy, but it seems that Taskotron is not yet in a position to really make the tighter policy viable.

**Comment by remicollet** [comment] 2018-01-24 05:13
Also https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2018-83d84f5a97

> The other suggestion we're kicking around is to invert the policy, so that an update is only blocked if one of the 'required' tests definitely failed, rather than always being blocked until all the 'required' tests definitely passed.

+1

**Comment by pypingou** [comment] 2018-01-24 08:21
There is also the work being done in https://github.com/fedora-infra/bodhi/pull/1779 (which needs to be re-done to integrate with [RATS](https://pagure.io/rats)) but that should help the whole situation.

**Comment by AdamWill** [comment] 2018-01-24 08:36
Unfortunately it's not quite that simple. That PR is basically about implementing a system by which Bodhi (or anything else) can request that the test which led to a result in resultsdb be re-run. It doesn't encompass the work of having the test system actually re-run the test.

For the openQA cases that happens to be pretty trivial; I'll be able to hook it up in minutes or hours once the system is in place. For some Taskotron tests, it is not. `dist.rpmdeplint` - one of the blocking tests - is actually one of the main cases here. The problem is that that test is not run "on a package" or even "on an update", it is run on a *repository*; basically it's run every time the `updates-testing-pending` tag (I think that's the name) is refreshed, on every package in that tag. The results of that test are then sort of 'translated' into results filed in resultsdb by package: something looks at the outcome of the actual test tool, identifies packages for which some kind of problem is indicated, and files an individual 'fail' result for each package (and a 'pass' result for each package present in the repo for which no problem was reported).

From there I guess the problem is pretty obvious: Bodhi can request "re-run this test" till it's blue in the face, but that's not something it's very easy for Taskotron to actually *do*. The context the test originally ran in doesn't exist any more and can't very easily be recreated.

@tflink says it is possible to come up with some kind of implementation of this, but it's not something that exists right now, and it's not just a trivial thing to implement; it'll take a bit of work.

**Comment by keszybz** [comment] 2019-03-11 06:28
The same result in https://bodhi.fedoraproject.org/updates/FEDORA-2019-60aa35e553. Comment says "This update has reached 3 days in testing and can be pushed to stable now if the maintainer wishes — a day ago", but there's no push button.

**Comment by bowlofeggs** [comment] 2019-03-11 16:11
On Sun, 2019-03-10 at 23:28 -0700, Zbigniew Jędrzejewski-Szmek wrote:
> The same result in 
> https://bodhi.fedoraproject.org/updates/FEDORA-2019-60aa35e553.
> Comment says "This update has reached 3 days in testing and can be
> pushed to stable now if the maintainer wishes — a day ago", but
> there's no push button.

This is a deployment configuration issue:

https://lists.fedoraproject.org/archives/list/infrastructure@lists.fedoraproject.org/thread/7X6B6BGFJ7SYZA243XOVPEJT7KVXRS24/

**Comment by bowlofeggs** [comment] 2019-03-11 16:32
On Sun, 2019-03-10 at 23:28 -0700, Zbigniew Jędrzejewski-Szmek wrote:
> The same result in 
> https://bodhi.fedoraproject.org/updates/FEDORA-2019-60aa35e553.
> Comment says "This update has reached 3 days in testing and can be
> pushed to stable now if the maintainer wishes — a day ago", but
> there's no push button.

This should be fixed in production now. Apologies for the
inconvenience.

**Closed as completed** 2019-06-12 19:59 UTC
