### ISSUE TITLE
Update reports 60 tests passed, and also that 1 of 55 failed

### ISSUE THREAD

**Issue by bcl** [fedora-infra/bodhi#5361] opened 2023-06-01 18:20 UTC
https://bodhi.fedoraproject.org/updates/FEDORA-2023-aaafb156ac

I'm seeing a green 60 at the top. On the right it says 1 of 55 failed. Clicking on either to get to the list of tests shows them all green. Nothing failed that I can tell...

**Comment by AdamWill** [comment] 2023-06-01 23:24
See https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/64WZOFFAPD4FRK7SDUYXHPEUBTNSBOWS/ - it's because of the Koji outage.

The issue is pretty much just that we didn't really write the web UI to handle this specific behaviour of greenwave, where it gives us an "unsatisfied requirement" that indicates an error. We don't exactly know what to do with it so it winds up looking a little weird. I'll see if I can hack up something to handle this better.

**Comment by AdamWill** [comment] 2023-06-02 00:20
Hum, so I'm looking at this and there's a few things to think about. There are a few related greenwave unsatisfied requirement types: failed-fetch-gating-yaml, invalid-gating-yaml and missing-gating-yaml . I immediately got sidetracked into what happens if you try to waive them: the answer is it fails awkwardly, because the Bodhi code assumes any unsatisfied requirement will have an `item` key, but these don't. In fact, the `item` key in unsatisfied requirements which *do* have one is specifically marked as being "for backwards compatibility only" in greenwave - https://pagure.io/greenwave/blob/c6ab6b9546aa1ae039070d5a501b30d20d5fb5e4/f/greenwave/policies.py#_259 - so we might be supposed to be doing something else [here](https://github.com/fedora-infra/bodhi/blob/11bcf08080a187cad8f3d9685f6ec980555d3ae0/bodhi-server/bodhi/server/models.py#L3254). But anyhoo - *should* we be trying to waive these types of unsatisfied requirement, or should we consider them unwaivable? I'm not sure.

@hluk what should bodhi be doing instead of using `requirement['item']`? Should it just use `requirement['subject_type']` and `requirement['subject_identifier']`?

**Comment by hluk** [comment] 2023-06-02 04:50
> what should bodhi be doing instead of using `requirement['item']`? Should it just use `requirement['subject_type']` and `requirement['subject_identifier']`?

Yes please. Properties `subject_type` and `subject_identifier` are the meant to replace the `item` and make the requirement entries consistent.

Looks like I will have to update the docs: https://gating-greenwave.readthedocs.io/en/latest/decision_requirements.html#examples
("test-result-failed" and "test-result-errored" also contain the new properties)

**Closed as completed** 2023-07-29 09:12 UTC
