### ISSUE TITLE
Bodhi2 no longer informs me about the possibility to push to stable

### ISSUE THREAD

**Issue by strzibny** [fedora-infra/bodhi#370] opened 2015-08-26 08:39 UTC
Bodhi always inserted a comment informing me about the possibility to push to stable e.g.:
```
This update has reached 7 days in testing and can be pushed to stable now if the maintainer wishes
```
But now it does not. Example: https://bodhi.fedoraproject.org/updates/rubygem-listen-3.0.3-1.fc23%20rubygem-rerun-0.10.0-3.fc23.

**Comment by voxik** [comment] 2015-08-26 10:23
Please note that there used to be comment about this as well as email/fedmsg notification, but neither of this is true anymore.

**Comment by lmacken** [comment] 2015-08-26 15:08
Duplicate of #298

**Closed** 2015-08-26 15:09 UTC
