### ISSUE TITLE
unable to find any packages that match the current query

### ISSUE THREAD

**Issue by adelton** [fedora-infra/bodhi#1764] opened 2017-08-19 09:36 UTC
When attempting to create new errata via https://bodhi.fedoraproject.org/updates/new, I enter perl-SOAP-Lite to the Packages field, and I get

```
unable to find any packages that match the current query
```

popup instead of that package name being confirmed.

The `perl-SOAP-Lite` package exists, per https://koji.fedoraproject.org/koji/packageinfo?packageID=3213

**Comment by jeremycline** [comment] 2017-08-23 13:28
I believe this is a duplicate of #1731, a regression introduced in 2.9.0. It was expected that 2.10.0 would contain the fix, but it seems to still be an issue. I'm going to close this in favor #1731.

Thanks for the report!

**Closed as completed by jeremycline** 2017-08-23 13:28 UTC
