### ISSUE TITLE
RFE: Listing updates in pending, testing, processing phases together

### ISSUE THREAD

**Issue by zdohnal** [fedora-infra/bodhi#1804] opened 2017-09-13 06:52 UTC
Hi,
I found out when I want to list my updates for several phase at once, AFAIK it is not possible. Would you mind adding this feature, so when I want to list my updates, which aren't in stable, so I could use option like "--status pending,testing,processing"?

**Comment by bowlofeggs** [comment] 2019-05-02 15:31
This is a duplicate of #1786, so let's track it there.

**Closed as completed by bowlofeggs** 2019-05-02 15:31 UTC
Labels: RFE, API, Client
