### ISSUE TITLE
update email notifications no longer contain NEVR in the subject

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/bodhi#1657] opened 2017-06-28 10:34 UTC
Previously, the full NEVR of the update was part of the subject line, which resulted in e-mail clients neatly organizing all emails for one update into one thread. Now all updates for the same package (regardless of version, release) are sorted into the same thread (because of the same subject line).

**Comment by ryanlerch** [comment] 2017-06-28 13:15
Thanks for taking the time to report this issue! Good news, this one has already been reported and fixed in develop, and will be included in the next release of bodhi. 

Duplicate of #1635

**Closed as completed by ryanlerch** 2017-06-28 13:15 UTC
