### ISSUE TITLE
Vagrant bootstrap fails during 'bodhi: Setting hostname...'

### ISSUE THREAD

**Issue by tserafim** [fedora-infra/bodhi#1607] opened 2017-06-15 02:19 UTC
I cloned the repo and followed the procedures to create a development environment. After executing vagrant up command, an error occurs:

    ==> bodhi: Setting hostname...
    The following SSH command responded with a non-zero exit status.
    Vagrant assumes that this means the command failed!
    
    # Update sysconfig
    sed -i 's/\(HOSTNAME=\).*/\1bodhi-dev.example.com/' /etc/sysconfig/network
    
    # Update DNS
    sed -i 's/\(DHCP_HOSTNAME=\).*/\1"bodhi-dev"/' /etc/sysconfig/network-scripts/ifcfg-*
    
    # Set the hostname - use hostnamectl if available
    echo 'bodhi-dev.example.com' > /etc/hostname
    if command -v hostnamectl; then
      hostnamectl set-hostname --static 'bodhi-dev.example.com'
      hostnamectl set-hostname --transient 'bodhi-dev.example.com'
    else
      hostname -F /etc/hostname
    fi
    
    # Remove comments and blank lines from /etc/hosts
    sed -i'' -e 's/#.*$//' -e '/^$/d' /etc/hosts
    
    # Prepend ourselves to /etc/hosts
    grep -w 'bodhi-dev.example.com' /etc/hosts || {
      sed -i'' '1i 127.0.0.1\tbodhi-dev.example.com\tbodhi-dev' /etc/hosts
    }
    
    # Restart network
    service network restart
    
    
    Stdout from the command:
    
    /bin/hostnamectl
    Restarting network (via systemctl):  [FAILED]
    
    
    Stderr from the command:
    
    Job for network.service failed because the control process exited with error code.
    See "systemctl status network.service" and "journalctl -xe" for details.

I succesfully sshed into the virtual machine and tried to restart the network service:

    [vagrant@bodhi-dev ~]$ service network restart
    Restarting network (via systemctl):  Failed to restart network.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
    See system logs and 'systemctl status network.service' for details.
                                                               [FAILED]

To test, I reboot the virtual machine and sshed into it again. The network service was active

**Comment by brandongray** [comment] 2017-06-15 03:36
Yep, I'm seeing the same issue.  I haven't looked too much into it but have noticed a `vagrant reload` will continue on with the provisioning.  Although, I see one of the ansible tasks fails with a python exception.

**Comment by bowlofeggs** [comment] 2017-06-15 14:47
I am not able to reproduce this issue myself. What host OS are each of you running, and what versions of vagrant and vagrant-libvirt do you have? Also, do you have the same checksum that I do here?

```
$ rpm -q vagrant-libvirt vagrant
vagrant-libvirt-0.0.35-3.fc25.noarch
vagrant-1.8.5-3.fc25.noarch
$ sha512sum ~/.vagrant.d/boxes/f25-cloud-libvirt/0/libvirt/box.img 
3866b6e7aa587e6a8aa41df93bb88c5226a6e131d435ddcd6d39764ec5aba281a73a011d1ca1b827e424ebdfc5c26451cfb15b2c55a4f635a7a0d9ef4d47dd0a  /home/rbarlow/.vagrant.d/boxes/f25-cloud-libvirt/0/libvirt/box.img
```

**Comment by tserafim** [comment] 2017-06-15 17:14
I am using a Fedora 25 host. My vagrant  and vagrant-libvirt versions matches the ones on your post.
The checksum also matches.

    sha512sum ~/.vagrant.d/boxes/f25-cloud-libvirt/0/libvirt/box.img
    3866b6e7aa587e6a8aa41df93bb88c5226a6e131d435ddcd6d39764ec5aba281a73a011d1ca1b827e424ebdfc5c26451cfb15b2c55a4f635a7a0d9ef4d47dd0a  /home/serafim/.vagrant.d/boxes/f25-cloud-libvirt/0/libvirt/box.img

I can confirm what @brandongray said, `vagrant reload` does continue with provisioning.
A failure happens during ansible task - apply database migrations....but i guess that's another issue.

By the way, all this is on branch `develop`

**Comment by bowlofeggs** [comment] 2017-06-15 23:34
What error do you see when the database migrations are applied?

**Comment by tserafim** [comment] 2017-06-16 01:36
I did a dnf upgrade on my host machine and several packages related to libvirt were upgraded. After that, I did a vagrant destroy and vagrant up, and the error related to `==> bodhi: Setting hostname...` does not happen anymore. 

List of updated packages:

    Upgraded libvirt-2.2.1-1.fc25.x86_64                                     @updates
        Upgraded libvirt-client-2.2.1-1.fc25.x86_64                              @updates
        Upgraded libvirt-daemon-2.2.1-1.fc25.x86_64                              @updates
        Upgraded libvirt-daemon-config-network-2.2.1-1.fc25.x86_64               @updates
        Upgraded libvirt-daemon-config-nwfilter-2.2.1-1.fc25.x86_64              @updates
        Upgraded libvirt-daemon-driver-interface-2.2.1-1.fc25.x86_64             @updates
        Upgraded libvirt-daemon-driver-libxl-2.2.1-1.fc25.x86_64                 @updates
        Upgraded libvirt-daemon-driver-lxc-2.2.1-1.fc25.x86_64                   @updates
        Upgraded libvirt-daemon-driver-network-2.2.1-1.fc25.x86_64               @updates
        Upgraded libvirt-daemon-driver-nodedev-2.2.1-1.fc25.x86_64               @updates
        Upgraded libvirt-daemon-driver-nwfilter-2.2.1-1.fc25.x86_64              @updates
        Upgraded libvirt-daemon-driver-qemu-2.2.1-1.fc25.x86_64                  @updates
        Upgraded libvirt-daemon-driver-secret-2.2.1-1.fc25.x86_64                @updates
        Upgraded libvirt-daemon-driver-storage-2.2.1-1.fc25.x86_64               @updates
        Upgraded libvirt-daemon-driver-uml-2.2.1-1.fc25.x86_64                   @updates
        Upgraded libvirt-daemon-driver-vbox-2.2.1-1.fc25.x86_64                  @updates
        Upgraded libvirt-daemon-driver-xen-2.2.1-1.fc25.x86_64                   @updates
        Upgraded libvirt-daemon-kvm-2.2.1-1.fc25.x86_64                          @updates
        Upgraded libvirt-libs-2.2.1-1.fc25.x86_64                                @updates


But the ansible playbook still fails on the apply database migrations task.

Ansible error report finishes with:

    "ValueError: Invalid config values were set: ", "\tmash_dir: \"/home/vagrant/bodhi/bodhi/server/../../masher/mash\" does not exist.", "\tmash_stage_dir: \"/home/vagrant/bodhi/bodhi/server/../../masher\" does not exist."], "stdout": "", "stdout_lines": []}
I sshed into the machine and tried to do a manual database migration. Same error.

    $ vagrant ssh
    [vagrant@bodhi-dev ~]$ cd bodhi/
    [vagrant@bodhi-dev bodhi]$ alembic upgrade head
    Traceback (most recent call last):
      File "/usr/bin/alembic", line 9, in <module>
        load_entry_point('alembic==0.8.6', 'console_scripts', 'alembic')()
      File "/usr/lib/python2.7/site-packages/alembic/config.py", line 479, in main
        CommandLine(prog=prog).main(argv=argv)
      File "/usr/lib/python2.7/site-packages/alembic/config.py", line 473, in main
        self.run_cmd(cfg, options)
      File "/usr/lib/python2.7/site-packages/alembic/config.py", line 456, in run_cmd
        **dict((k, getattr(options, k)) for k in kwarg)
      File "/usr/lib/python2.7/site-packages/alembic/command.py", line 174, in upgrade
        script.run_env()
      File "/usr/lib/python2.7/site-packages/alembic/script/base.py", line 397, in run_env
        util.load_python_file(self.dir, 'env.py')
      File "/usr/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
        module = load_module_py(module_id, path)
      File "/usr/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
        mod = imp.load_source(module_id, path, fp)
      File "alembic/env.py", line 17, in <module>
        config.set_main_option("sqlalchemy.url", bodhi_config["sqlalchemy.url"])
      File "/home/vagrant/bodhi/bodhi/server/config.py", line 557, in __getitem__
        self.load_config()
      File "/home/vagrant/bodhi/bodhi/server/config.py", line 590, in load_config
        self._validate()
      File "/home/vagrant/bodhi/bodhi/server/config.py", line 608, in _validate
        'Invalid config values were set: \n{}'.format('\n'.join(errors)))
    ValueError: Invalid config values were set: 
    	mash_dir: "/home/vagrant/bodhi/bodhi/server/../../masher/mash" does not exist.
    	mash_stage_dir: "/home/vagrant/bodhi/bodhi/server/../../masher" does not exist.
    [vagrant@bodhi-dev bodhi]$

**Comment by brandongray** [comment] 2017-06-16 03:10
FWIW, I'm updated to libvirt* 2.2.1-2 and still seeing both issues.

**Comment by brandongray** [comment] 2017-06-16 14:19
I see this same hostname error in another project (cockpit) and have found some others with the same issue (potentially in box race condition).  As for the ansible/alembic error, it looks like the directories just need to exist (mkdir -p masher/mash).  It's in .gitignore so I'm guessing that's why @bowlofeggs couldn't reproduce.

**Comment by tserafim** [comment] 2017-06-16 17:00
@brandongray indeed, ansible provisioning was succesfull after creating those folders.

**Comment by bowlofeggs** [comment] 2017-06-16 17:30
@tserafim you are in luck with the new error - I actually just happened to notice that one yesterday, and I have an open PR to fix it:

https://github.com/fedora-infra/bodhi/pull/1612

**Comment by tserafim** [comment] 2017-07-29 15:18
I just created another dev environment and the provisioners ran successfully. None of the problems mentioned above occurred.

Running Fedora 26 with the following versions of libvirt, libvit-vagrant and vagrant:
libvirt-3.2.1-4.fc26.x86_64
vagrant-libvirt-0.0.37-5.fc26.noarch
vagrant-1.9.1-2.fc26.noarch

I guess #1617 solved the database migration issue.

**Comment by bowlofeggs** [comment] 2017-07-29 16:04
Excellent, I will close this issue for now then. Let me know if you hit any more problems!

**Closed as completed by bowlofeggs** 2017-07-29 16:04 UTC
