### ISSUE TITLE
Problems running "yum check-update" with epel-testing on CentOS 7

### ISSUE THREAD

**Issue by avantsysadm** [fedora-infra/bodhi#3937] opened 2020-02-28 16:26 UTC
Hi there,

The Red Hat Bugzilla folks pointed us in this direction, and I tried getting some help on a similar issue here only to find out that the member in that thread isn't working on this anymore.

We've run into some issues on one of our CentOS 7 hosts that's spitting out issues with the epel-testing repo complaining of corrupt metadata (update times). This was also happening on epel-testing-source but we were able to disable that repo for now. We're getting these errors constantly in email via hourly cron jobs so it would be nice to get to the bottom of this. 

Our error output from **yum check-update**

> Update notice FEDORA-EPEL-2019-b1b73eda91 (from epel-testing) is broken, or a bad duplicate, skipping.
> You should report this problem to the owner of the epel-testing repository.
> If you are the owner, consider re-running the same command with --verbose to see the exact data that caused the conflict.
> Update notice FEDORA-EPEL-2019-c44b218d4a (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-d6bedfa33e (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-6c9bd69e8c (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-17d2b3507b (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-d08cc0cf56 (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-63395bd546 (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-b3b252ad49 (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-936f369393 (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-77e03a194b (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-caf5e780e6 (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-a6e87b96c1 (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-0ad24584d8 (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-f457d4367d (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-f84c232513 (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-8cbc520a97 (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-d50307dc61 (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-10c651b6cf (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-d49efff651 (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-1e0469226c (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-906483cc2f (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-3221ff1dea (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-8618614749 (from epel-testing) is broken, or a bad duplicate, skipping.
> Update notice FEDORA-EPEL-2019-7d7926ef71 (from epel-testing) is broken, or a bad duplicate, skipping.

Let me know if there's anything else I can add to help aid in troubleshooting this issue.

Tyler

**Comment by mattiaverga** [comment] 2022-11-17 14:21
Dupe of #2487

**Closed as completed by mattiaverga** 2022-11-17 14:21 UTC
Labels: Critical, Composer
