### ISSUE TITLE
duplicated comments about package being pushed to stable

### ISSUE THREAD

**Issue by keszybz** [fedora-infra/bodhi#1665] opened 2017-06-30 16:21 UTC
I noticed this on all recent updates. Taking https://bodhi.fedoraproject.org/updates/FEDORA-2017-956e27bdd6 as an example, I got the following mails:

```
Date: Thu, 29 Jun 2017 10:06:26 +0000 (UTC)                                                             
From: updates@fedoraproject.org                                                                         
To: zbyszek@in.waw.pl                                                                                   
Subject: [Fedora Update] [CRITPATH] [comment] systemd                                                   
                                                                                                        
The following comment has been added to the systemd-233-6.fc26 update:                                  
                                                                                                        
bodhi - 2017-06-29 10:06:26.322215 (karma: 0)                                                           
This update has been submitted for stable by bodhi.                                                     
```

```
Date: Thu, 29 Jun 2017 10:06:28 +0000 (UTC)                                                             
From: updates@fedoraproject.org                                                                         
To: zbyszek@in.waw.pl                                                                                   
Subject: [Fedora Update] [CRITPATH] [comment] systemd                                                   
Return-path: <updates@fedoraproject.org>                                                                
                                                                                                        
The following comment has been added to the systemd-233-6.fc26 update:                                  
                                                                                                        
bodhi - 2017-06-29 10:06:26.322215 (karma: 0)                                                           
This update has been submitted for stable by bodhi.                                                     
```
The web interface shows the comment just one time, so maybe it's just the notification mechanism that is confused.

**Comment by bowlofeggs** [comment] 2017-06-30 20:59
This is a duplicate of https://github.com/fedora-infra/bodhi/issues/1403 so I'm going to close this one. Thanks for reporting!

**Closed as completed by bowlofeggs** 2017-06-30 20:59 UTC
