### ISSUE TITLE
Cannot find package on epel7

### ISSUE THREAD

**Issue by tomspur** [fedora-infra/bodhi#643] opened 2015-10-08 17:10 UTC
I just tried to update `epel-rpm-macros` and couldn't do that online but with `fedpkg update` everything was fine.

Problems with the web interface:
- Entering `epel` in the update dialog to find the above package does not show it at all and because of that, I cannot ship an update of it.
- Enering `epel` in the search view, I can select the right package, but I'm forwarded to a [user page](https://bodhi.fedoraproject.org/users/epel-rpm-macros) instead the package url.

Maybe this has something to do that this package does not exist on Fedora?

**Comment by tomspur** [comment] 2015-10-09 07:08
With the new `bodhi-2.1.2` the second issue with the user page is fixed. I still cannot find the package, when entering it in the update dialog.

**Comment by ralphbean** [comment] 2015-10-11 18:52
> Entering epel in the update dialog to find the above package does not show it at all and because of that, I cannot ship an update of it.

You already have a workaround -- using ``fedpkg``.  However, another workaround:  you can type ``epel-rpm-macros-7-4`` directly into the 'candidate builds' field in the new update form, press ``<enter>`` and a checkbox item should be added for it (bypassing the auto-population done by the search field).

This doesn't excuse the absence of ``epel-rpm-macros`` from the search results though.  The cause of that has to do with failures in [the fedora-packages system](https://apps.fedoraproject.org/packages/s/epel-rpm-macros).  Those will hopefully be fixed in the next month or so.

**Comment by tomspur** [comment] 2015-10-12 08:14
Thanks. I just wanted to make sure that it is reported also.

**Comment by jnpkrn** [comment] 2015-10-14 12:59
Somewhat similar issue, `libqb` package seems unrecognized by new bodhi: https://bodhi.fedoraproject.org/updates/libqb although it is known to other infrastructure services just fine: https://apps.fedoraproject.org/packages/libqb

**Comment by jnpkrn** [comment] 2015-10-14 13:20
This seems working as expected https://bodhi.fedoraproject.org/updates/?packages=libqb (thanks @pypingou).

**Comment by jnpkrn** [comment] 2015-10-14 13:22
Note that `libqb` is recognized in the search box of Create update dialog.

**Comment by jnpkrn** [comment] 2015-10-14 13:27
The problem with `updates/libqb` URL (404 Not Found // Invalid update id) is likely related to the fact there hasn't been any update for that component, i.e., it was updated via "automatically maturing from rawhide").

**Comment by jnpkrn** [comment] 2015-10-19 09:22
Note that last 4 comments are no longer valid for libqb since I've actually sent a new update for libqb, but I guess you can still find a package with no update whatsoever to reproduce the issue that should rather be fixed so as to prevent confusion.

**Comment by bowlofeggs** [comment] 2018-12-12 16:21
I believe Bodhi's integration with pkgdb is working as expected, so I am closing this. Let me know if you still experience this problem.

**Closed by bowlofeggs** 2018-12-12 16:21 UTC
