### ISSUE TITLE
Bodhi comments now display extraneous \n characters

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#147] opened 2015-06-04 18:16 UTC
Taskotron comments now display extraneous `\n` characters:

> taskotron - 2015-06-03 20:17:35
Taskotron: depcheck test PASSED on i386. Result log:\nhttps://taskotron.fedoraproject.org/taskmaster//builders/x86_64/builds/76687/steps/runtask/logs/stdio\n(results are informative only) 

https://admin.fedoraproject.org/updates/xorg-x11-drv-intel-2.99.917-11.20150603.fc22

@lmacken looked at this and says it is caused by commit b28f95f0b27141d92ac9abcd3a23718cff054c53 . 

I have tried to traverse old comments in Bodhi and it seems that it broke around Dec 2014 to Jan 2015. See this update, the old comments are fine, the newer one is not:
https://admin.fedoraproject.org/updates/FEDORA-2014-16953/perl-YAML-Syck-1.28-1.fc20

**Comment by lmacken** [comment] 2015-06-04 18:18
I don't think it's caused by that commit, but I think we may need to port that commit to the comment text.

**Comment by lmacken** [comment] 2015-06-04 18:34
This is the ticket that was filed previously when this happened with the update notes. https://fedorahosted.org/bodhi/ticket/767

**Comment by lmacken** [comment] 2015-06-04 21:41
Just pushed this to stg and it looks like it does the trick...

https://admin.stg.fedoraproject.org/updates/tmux-1.9a-5.fc21

**Comment by lmacken** [comment] 2015-06-04 21:52
Fixed in production with 0.9.17. Thanks for the report!

**Closed by lmacken** 2015-06-04 21:52 UTC

**Comment by kparal** [comment] 2015-06-05 05:56
Thanks for a quick response.
