### ISSUE TITLE
bodhi updates new does not work

### ISSUE THREAD

**Issue by belegdol** [fedora-infra/bodhi#1481] opened 2017-04-26 22:04 UTC
Hello,

I have installed bodhi-2.6.0-1.fc25 from copr repo. Unfortunately it appears that bodhi updates new does not work anymore:
```
$ bodhi updates new --user belegdol mame-0.185-1.fc26
Password: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bodhi/client/__init__.py", line 132, in new
    resp = client.save(**update)
  File "/usr/lib/python2.7/site-packages/bodhi/client/bindings.py", line 66, in wrapper
    result = method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bodhi/client/bindings.py", line 161, in save
    data=kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 254, in send_request
    'output': to_bytes(output.text),
ServerError: ServerError(https://bodhi.fedoraproject.org/updates/, 403, Error returned from json module while processing https://bodhi.fedoraproject.org/updates/: Expecting value: line 6 column 1 (char 5)





<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="management of Fedora Project updates" />
    <meta name="author" content="Luke Macken" />
    <meta name="author" content="Ralph Bean" />

    <!-- Only allow websockets connections to fedoraproject.org. -->
    <meta http-equiv="Content-Security-Policy" content="connect-src https://*.fedoraproject.org/ wss://hub.fedoraproject.org:9939/">

    <link rel="shortcut icon" href="https://bodhi.fedoraproject.org/static/ico/favicon.ico">

    <base href="https://bodhi.fedoraproject.org/"/>
    <title>
      
      Fedora Updates System
      
    </title>
    <link href="https://bodhi.fedoraproject.org/static/fedora-bootstrap-1.0.1/fedora-bootstrap.css" rel="stylesheet" />
    <link href="https://bodhi.fedoraproject.org/static/fonts/open-sans.css" rel="stylesheet" />
    <link href="https://bodhi.fedoraproject.org/static/fonts/hack.css" rel="stylesheet" />
    <link href="https://bodhi.fedoraproject.org/static/fonts/font-awesome.css" rel="stylesheet" />
    <link href="https://bodhi.fedoraproject.org/static/css/text.css" rel="stylesheet" />
    <link href="https://bodhi.fedoraproject.org/static/css/navbar.css" rel="stylesheet" />
    <link href="https://bodhi.fedoraproject.org/static/css/footer.css" rel="stylesheet" />
    <link href="https://bodhi.fedoraproject.org/static/css/site.css" rel="stylesheet" />
    <link href="https://bodhi.fedoraproject.org/static/css/datagrepper-feed.css" rel="stylesheet" />
    <link href="https://bodhi.fedoraproject.org/static/css/panel.css" rel="stylesheet" />
    <script src="https://bodhi.fedoraproject.org/static/js/jquery-1.10.2.min.js"></script>
    <script src="https://bodhi.fedoraproject.org/static/js/Chart-0.2.0.min.js"></script>
  </head>

  <body>
      <div class="searchbar" style="display:none;">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <form id="search" role="search" class="nav navbar-form navbar-left">
                <div id="bloodhound" class="form-group m-b-0">
                  <input class="typeahead form-control" name="term" type="text" placeholder="Search..." style="height:50px;background:rgba(0,0,0,0);border:0;color:white;line-height:50px;">
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <div class="masthead">
      <div class="container">
        <div class="row">
          <div class="col-sm-6">
            <a href="https://bodhi.fedoraproject.org/">
              <img src="https://bodhi.fedoraproject.org/static/img/bodhi-logo.png" alt="Fedora Update System" id="kojiLogo" height="40px">
            </a>
          </div>
          <div class="col-sm-6">
            <div class="row">
              <nav class="navbar navbar-light p-t-0 p-b-0">
                  <div class="container">
                    <ul class="nav navbar-nav nav-pill pull-xs-right">

                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <span class="glyphicon glyphicon-tags"></span>
                            Releases
                          </a>
                          <div class="dropdown-menu">
                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/metrics">
                              Overall Metrics
                            </a>
                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/masher/">
                              Masher Status
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F25">
                              Fedora 25
                            </a>
                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F24">
                              Fedora 24
                            </a>
                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/EPEL-7">
                              Fedora EPEL 7
                            </a>
                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/EL-6">
                              Fedora EPEL 6
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F23">
                              Fedora 23
                            </a>
                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F22">
                              Fedora 22
                            </a>
                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F21">
                              Fedora 21
                            </a>
                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/EL-5">
                              Fedora EPEL 5
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="https://bodhi.fedoraproject.org/releases/F26">
                              Fedora 26
                            </a>
                          </div>
                        </li>


                        <li class="nav-item">
                          <a class="nav-link" href="https://bodhi.fedoraproject.org/login?came_from=https://bodhi.fedoraproject.org/updates/">
                            <span class="glyphicon glyphicon-log-in"></span>
                            Login</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="javascript:void(0);" id="search-toggle">
                            <span class="fa fa-search"></span>
                          </a>
                        </li>
                    </ul>
                  </div>
                </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="bodycontent p-b-3">
        

<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <div class="panel error-page-panel">
      <h1>403 <small>Forbidden</small></h1>
      <p class="lead">Access was denied to this resource.</p>
    </div>
  </div>
</div>

    </div> <!-- /bodycontent -->

    <div class="footer p-y-3">
      <div class="container">
        <p class="text-muted text-xs-center">
          Copyright &copy; 2007-2017 Red Hat, Inc. and
          <a href="https://github.com/fedora-infra/bodhi/graphs/contributors">
          others</a>.
        </p>
        <p class="text-muted text-xs-center">
          Running
          <strong>bodhi-2.6.0</strong> on
          <strong>bodhi04.phx2.fedoraproject.org</strong>.
        </p>
        <p class="text-muted text-xs-center">
          <a href="https://github.com/fedora-infra/bodhi">
          bodhi</a> is Free Software.
          Please <a href="https://github.com/fedora-infra/bodhi/issues">
          file issues</a>
          if you have any problems. Read the <a href="https://bodhi.fedoraproject.org/docs">documentation</a>.
        </p>
      </div>
    </div>

    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://bodhi.fedoraproject.org/static/jquery.flot.js"></script>
    <script src="https://bodhi.fedoraproject.org/static/jquery.flot.stack.js"></script>
    <script src="https://bodhi.fedoraproject.org/static/fedora-bootstrap-1.0.1/fedora-bootstrap.js"></script>
    <script src="https://bodhi.fedoraproject.org/static/moment/moment.min.js"></script>
    <script src="https://bodhi.fedoraproject.org/static/js/cabbage.js"></script>
    <script src="https://bodhi.fedoraproject.org/static/js/forms.js"></script>
    <script src="https://bodhi.fedoraproject.org/static/js/site.js"></script>
    <script src="https://bodhi.fedoraproject.org/static/messenger/js/messenger.min.js"></script>
    <script src="https://bodhi.fedoraproject.org/static/messenger/js/messenger-theme-flat.js"></script>
    <link href="https://bodhi.fedoraproject.org/static/messenger/css/messenger.css" rel="stylesheet" />
    <link href="https://bodhi.fedoraproject.org/static/messenger/css/messenger-theme-flat.css" rel="stylesheet" />
    <script src="https://bodhi.fedoraproject.org/static/js/typeahead.bundle.js"></script>
    <script src="https://bodhi.fedoraproject.org/static/js/search.js"></script>
    <script src="https://bodhi.fedoraproject.org/static/js/konami.js"></script>

    <script src="https://apps.fedoraproject.org/fedmenu/js/fedora-libravatar.js"></script>
    <script src="https://apps.fedoraproject.org/fedmenu/js/fedmenu.js"></script>
    <script>
      fedmenu({
          'url': 'https://apps.fedoraproject.org/js/data.js',
          'mimeType': 'application/javascript',
          'position': 'bottom-right',
      });
    </script>

  </body>
</html>
)
```

**Comment by bowlofeggs** [comment] 2017-04-26 22:27
Thanks for the report! This is a duplicate of https://github.com/fedora-infra/bodhi/issues/1474 so let's track it there.

**Closed as completed by bowlofeggs** 2017-04-26 22:27 UTC

**Comment by bowlofeggs** [comment] 2017-04-26 22:30
Note: you can work around this issue by using this every time it happens:

```
$ rm ~/.fedora/openidbaseclient-sessions.cache
```
