### ISSUE TITLE
yum check-update fails with "update notice FEDORA-EPEL (from epel) is broken, or a bad duplicate, skipping."

### ISSUE THREAD

**Issue by marcelomarques74** [fedora-infra/bodhi#4826] opened 2022-11-11 00:10 UTC
```
# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)

# yum check-update
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-
              : manager

postgresql11.x86_64                       11.18-1PGDG.rhel7               pgdg11
postgresql11-contrib.x86_64               11.18-1PGDG.rhel7               pgdg11
postgresql11-libs.x86_64                  11.18-1PGDG.rhel7               pgdg11
postgresql11-server.x86_64                11.18-1PGDG.rhel7               pgdg11
postgresql12.x86_64                       12.13-1PGDG.rhel7               pgdg12
postgresql12-contrib.x86_64               12.13-1PGDG.rhel7               pgdg12
postgresql12-libs.x86_64                  12.13-1PGDG.rhel7               pgdg12
postgresql12-server.x86_64                12.13-1PGDG.rhel7               pgdg12
postgresql13.x86_64                       13.9-1PGDG.rhel7                pgdg13
postgresql13-contrib.x86_64               13.9-1PGDG.rhel7                pgdg13
postgresql13-libs.x86_64                  13.9-1PGDG.rhel7                pgdg13
postgresql13-server.x86_64                13.9-1PGDG.rhel7                pgdg13
Update notice FEDORA-EPEL-2020-84a1579a07 (from epel) is broken, or a bad duplicate, skipping.
You should report this problem to the owner of the epel repository.
To help pinpoint the issue, please attach the output of "yum updateinfo --verbose" to the report.
...
...

# yum updateinfo -verbose
Not loading "rhnplugin" plugin, as it is disabled
Loading "langpacks" plugin
Loading "product-id" plugin
Loading "search-disabled-repos" plugin
Loading "subscription-manager" plugin
Adding en_US.UTF-8 to language list
Updating Subscription Management repositories.
Config time: 0.676
Adding en_US to language list
Yum version: 3.4.3
rpmdb time: 0.000
Setting up Package Sacks
pkgsack time: 0.383
Duplicate of FEDORA-EPEL-2020-84a1579a07 differs in some fields:
<<<<<<< epel:rights
'Copyright (C) 2022 Red Hat, Inc. and others.'
=======
'Copyright (C) 2021 Red Hat, Inc. and others.'
>>>>>>> ESRI_EPEL_7_x86_64:rights
Update notice FEDORA-EPEL-2020-84a1579a07 (from epel) is broken, or a bad duplicate, skipping.
You should report this problem to the owner of the epel repository.
To help pinpoint the issue, please attach the output of "yum updateinfo --verbose" to the report.
Duplicate of FEDORA-EPEL-2018-3d4ca5935a differs in some fields:
<<<<<<< epel:rights
'Copyright (C) 2022 Red Hat, Inc. and others.'
=======
'Copyright (C) 2021 Red Hat, Inc. and others.'
>>>>>>> ESRI_EPEL_7_x86_64:rights
Update notice FEDORA-EPEL-2018-3d4ca5935a (from epel) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2015-69e0675e45 differs in some fields:
<<<<<<< epel:rights
'Copyright (C) 2022 Red Hat, Inc. and others.'
=======
'Copyright (C) 2021 Red Hat, Inc. and others.'
>>>>>>> ESRI_EPEL_7_x86_64:rights
Update notice FEDORA-EPEL-2015-69e0675e45 (from epel) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2018-b80060f45f differs in some fields:
<<<<<<< epel:rights
'Copyright (C) 2022 Red Hat, Inc. and others.'
=======
'Copyright (C) 2021 Red Hat, Inc. and others.'
>>>>>>> ESRI_EPEL_7_x86_64:rights
Update notice FEDORA-EPEL-2018-b80060f45f (from epel) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2015-0314 differs in some fields:
<<<<<<< epel:rights
'Copyright (C) 2022 Red Hat, Inc. and others.'
=======
'Copyright (C) 2021 Red Hat, Inc. and others.'
>>>>>>> ESRI_EPEL_7_x86_64:rights
Update notice FEDORA-EPEL-2015-0314 (from epel) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2022-3f443e2e1e differs in some fields:
<<<<<<< epel:issued
'2022-03-25 21:51:44'
=======

--------------------------------------------------------------------------------------------------------
Bug 1807091 - yum check-update fails with 
"update notice FEDORA-EPEL (from epel) is broken, or a bad duplicate, skipping."
https://bugzilla.redhat.com/show_bug.cgi?id=1807091
Kevin Fenzi 2020-02-25 23:46:55 UTC
This is a bug in bodhi (the fedora/epel updates system) that appears from time to time. ;( 
It's tracked in https://github.com/fedora-infra/bodhi/issues/2487
Can you add the above info there and hopefully bodhi developers will be able to track it down once and for all. 
Thanks for the report!
--------------------------------------------------------------------------------------------------------
```

**Comment by mmarquesesri** [comment] 2022-11-11 00:26
yum check-update fails with "update notice FEDORA-EPEL (from epel) is broken, or a bad duplicate, skipping." #4826
https://github.com/fedora-infra/bodhi/issues/4826

From: Marcelo Marques ***@***.***>
Sent: Thursday, November 10, 2022 4:10 PM
To: fedora-infra/bodhi ***@***.***>
Cc: Marcelo Marques ***@***.***>; Your activity ***@***.***>
Subject: [fedora-infra/bodhi] yum check-update fails with "update notice FEDORA-EPEL (from epel) is broken, or a bad duplicate, skipping." (Issue #4826)

cat /etc/redhat-release

Red Hat Enterprise Linux Server release 7.9 (Maipo)

yum check-update

Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-
: manager

postgresql11.x86_64 11.18-1PGDG.rhel7 pgdg11
postgresql11-contrib.x86_64 11.18-1PGDG.rhel7 pgdg11
postgresql11-libs.x86_64 11.18-1PGDG.rhel7 pgdg11
postgresql11-server.x86_64 11.18-1PGDG.rhel7 pgdg11
postgresql12.x86_64 12.13-1PGDG.rhel7 pgdg12
postgresql12-contrib.x86_64 12.13-1PGDG.rhel7 pgdg12
postgresql12-libs.x86_64 12.13-1PGDG.rhel7 pgdg12
postgresql12-server.x86_64 12.13-1PGDG.rhel7 pgdg12
postgresql13.x86_64 13.9-1PGDG.rhel7 pgdg13
postgresql13-contrib.x86_64 13.9-1PGDG.rhel7 pgdg13
postgresql13-libs.x86_64 13.9-1PGDG.rhel7 pgdg13
postgresql13-server.x86_64 13.9-1PGDG.rhel7 pgdg13
Update notice FEDORA-EPEL-2020-84a1579a07 (from epel) is broken, or a bad duplicate, skipping.
You should report this problem to the owner of the epel repository.
To help pinpoint the issue, please attach the output of "yum updateinfo --verbose" to the report.
...
...

yum updateinfo --verbose
Not loading "rhnplugin" plugin, as it is disabled
Loading "langpacks" plugin
Loading "product-id" plugin
Loading "search-disabled-repos" plugin
Loading "subscription-manager" plugin
Adding en_US.UTF-8 to language list
Updating Subscription Management repositories.
Config time: 0.676
Adding en_US to language list
Yum version: 3.4.3
rpmdb time: 0.000
Setting up Package Sacks
pkgsack time: 0.383
Duplicate of FEDORA-EPEL-2020-84a1579a07 differs in some fields:
<<<<<<< epel:rights
'Copyright (C) 2022 Red Hat, Inc. and others.'

'Copyright (C) 2021 Red Hat, Inc. and others.'

ESRI_EPEL_7_x86_64:rights
Update notice FEDORA-EPEL-2020-84a1579a07 (from epel) is broken, or a bad duplicate, skipping.
You should report this problem to the owner of the epel repository.
To help pinpoint the issue, please attach the output of "yum updateinfo --verbose" to the report.
Duplicate of FEDORA-EPEL-2018-3d4ca5935a differs in some fields:
<<<<<<< epel:rights
'Copyright (C) 2022 Red Hat, Inc. and others.'
=======
'Copyright (C) 2021 Red Hat, Inc. and others.'
ESRI_EPEL_7_x86_64:rights
Update notice FEDORA-EPEL-2018-3d4ca5935a (from epel) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2015-69e0675e45 differs in some fields:
<<<<<<< epel:rights
'Copyright (C) 2022 Red Hat, Inc. and others.'
=======
'Copyright (C) 2021 Red Hat, Inc. and others.'
ESRI_EPEL_7_x86_64:rights
Update notice FEDORA-EPEL-2015-69e0675e45 (from epel) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2018-b80060f45f differs in some fields:
<<<<<<< epel:rights
'Copyright (C) 2022 Red Hat, Inc. and others.'
=======
'Copyright (C) 2021 Red Hat, Inc. and others.'
ESRI_EPEL_7_x86_64:rights
Update notice FEDORA-EPEL-2018-b80060f45f (from epel) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2015-0314 differs in some fields:
<<<<<<< epel:rights
'Copyright (C) 2022 Red Hat, Inc. and others.'
=======
'Copyright (C) 2021 Red Hat, Inc. and others.'
ESRI_EPEL_7_x86_64:rights
Update notice FEDORA-EPEL-2015-0314 (from epel) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2022-3f443e2e1e differs in some fields:
<<<<<<< epel:issued
'2022-03-25 21:51:44'
=======

________________________________
Bug 1807091 - yum check-update fails with "update notice FEDORA-EPEL (from epel-testing) is broken, or a bad duplicate, skipping."
https://bugzilla.redhat.com/show_bug.cgi?id=1807091 [bugzilla.redhat.com]<https://urldefense.com/v3/__https:/bugzilla.redhat.com/show_bug.cgi?id=1807091__;!!CKZwjTOV!1uGoQR5wOoqZt7YSAysm2ZlF3_bQdyilar483vhWBXTfKX6W5XMKayGSbq4z-7CYf-XD9auESPg8RMy1uix7iw$>
Kevin Fenzi 2020-02-25 23:46:55 UTC
This is a bug in bodhi (the fedora/epel updates system) that appears from time to time. ;(
It's tracked in #2487 [github.com]<https://urldefense.com/v3/__https:/github.com/fedora-infra/bodhi/issues/2487__;!!CKZwjTOV!1uGoQR5wOoqZt7YSAysm2ZlF3_bQdyilar483vhWBXTfKX6W5XMKayGSbq4z-7CYf-XD9auESPg8RMwcfZ1yRA$>
Can you add the above info there and hopefully bodhi developers will be able to track it down once and for all.
Thanks for the report!

**Comment by mattiaverga** [comment] 2022-11-17 14:21
Dupe of #2487

**Closed as completed by mattiaverga** 2022-11-17 14:21 UTC
