### ISSUE TITLE
bodhi must not update product!=fedora bug states in bz.redhat.com

### ISSUE THREAD

**Issue by fche** [fedora-infra/bodhi#2315] opened 2018-04-24 19:42 UTC
A fedora package update accidentally mentioned a RHEL product bug# in its update text, and thus bodhi dutifully set its state to ON_QA as the bug went through the fedora update system.  This is wrong: RHEL bugs' states should be off limits to community software/bots like fedora's.  Please ensure that bodhi checks for Product=Fedora before changing bug states.  (Perhaps bz.redhat.com. should have an ACL that precludes the bodhi bot from doing this, but still.)

e.g. https://bugzilla.redhat.com/show_bug.cgi?id=1566422

**Comment by bowlofeggs** [comment] 2018-04-26 13:31
This is a duplicate of #1043 so let's track it there. Thanks!

**Closed as completed by bowlofeggs** 2018-04-26 13:31 UTC

**Comment by pcahyna** [comment] 2018-04-30 07:23
> Perhaps bz.redhat.com. should have an ACL that precludes the bodhi bot from doing this

https://bugzilla.redhat.com/show_bug.cgi?id=1483514
