### ISSUE TITLE
"Push to batched" button label is confusing

### ISSUE THREAD

**Issue by M4rtinK** [fedora-infra/bodhi#1905] opened 2017-10-17 17:07 UTC
With a recent Bodhi update there is no longer just the "push to stable" button but also a "push to batched" button. Both buttons also basically switch from to the other.

While it's rather intuitive what the "push to stable" button likely does - eq. pushes the update to a stable Fedora release, the  "push to batched" button sounds pretty cryptic.

While after doing some research I have discover what it does (pushes the update to a weekly update batch) I think this can still confuse a lot of user and is in general bad UX.

So I suggest renaming the button to "push to weekly batch".

While I understand Bodhi is used not only in Fedora and there might be different batch configurations elsewhere I still think this should be doable with a per-instance override. There is already a Fedora logo in the tile bar so it should be possible to also have a Fedora specific button label.

**Comment by bowlofeggs** [comment] 2017-10-17 17:10
We could probably make the text of the button be a setting so that Fedora's instance can say "Push in next weekly batch" or similar.

**Comment by M4rtinK** [comment] 2017-10-17 17:14
Yeah, that sounds even better. :)

**Comment by M4rtinK** [comment] 2017-10-17 17:16
But then it might make sense to also change the "push to stable" button in the same manner ? Eq. "Push in next daily push" ? That could make the whole thing much more clear. :)

**Comment by sfshameem5** [comment] 2017-11-12 13:38
How can I fix this issue ? Any help ?

**Comment by mattiaverga** [comment] 2018-04-06 15:40
What about something like this?
![screenshot_20180406_173011](https://user-images.githubusercontent.com/17218209/38430283-228b4974-39c1-11e8-955a-ddf544c0db64.png)
I think it's more clear, but would the button be too long in your judge?

**Comment by bowlofeggs** [comment] 2018-04-13 18:59
@mattiaverga The future of the batched feature is uncertain as [FESCo has been debating](https://pagure.io/fesco/issue/1820) what to do with it.

That said, I'd probably prefer a mouse hover pop up to changing the text. The problem is that when the batch or stable goes out is a matter of deployment configuration (i.e., uptsream Bodhi doesn't know that stable means next day or that batched means next Tuesday - that's a Fedora configuration). We can solve that problem by adding configuration for what text to put in the hoverover so each Bodhi deployment can customize the text for themselves.

In any case, I'd recommend waiting on FESCo's decision before expending effort here just in case they decide to get rid of the feature.

**Comment by bowlofeggs** [comment] 2018-04-13 19:16
@mattiaverga The future of the batched feature is uncertain as [FESCo has been debating](https://pagure.io/fesco/issue/1820) what to do with it.

That said, I'd probably prefer a mouse hover pop up to changing the text. The problem is that when the batch or stable goes out is a matter of deployment configuration (i.e., uptsream Bodhi doesn't know that stable means next day or that batched means next Tuesday - that's a Fedora configuration). We can solve that problem by adding configuration for what text to put in the hoverover so each Bodhi deployment can customize the text for themselves.

In any case, I'd recommend waiting on FESCo's decision before expending effort here just in case they decide to get rid of the feature.

**Comment by steaksauce-** [comment] 2018-10-27 00:27
Any updates on this?

**Comment by bowlofeggs** [comment] 2018-10-29 15:49
@steaksauce- no new information - the FESCo ticket is still in limbo so the batched feature is also in limbo.

**Comment by bowlofeggs** [comment] 2019-02-12 15:39
We are dropping the batching feature in #2977 so I will close this issue. Thanks for the report!

**Closed as completed by bowlofeggs** 2019-02-12 15:39 UTC
Labels: EasyFix, RFE, WebUI
