### ISSUE TITLE
Crash while looking for override candidates

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3274] opened 2019-05-31 17:23 UTC
Bodhi's web server occasionally crashes with this traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/usr/lib/python3.7/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/usr/lib/python3.7/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/usr/lib/python3.7/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/usr/lib/python3.7/site-packages/pyramid/viewderivers.py", line 148, in _requestonly_view
    response = view(request)
  File "/usr/lib/python3.7/site-packages/bodhi/server/views/generic.py", line 309, in latest_candidates
    result = work(pkg, testing)
  File "/usr/lib/python3.7/site-packages/bodhi/server/views/generic.py", line 291, in work
    for build in taglist[0]:
KeyError: 0
referer: https://bodhi.fedoraproject.org/overrides/new
```

The line in question is https://github.com/fedora-infra/bodhi/blob/4.0.2/bodhi/server/views/generic.py#L291 and it's pretty clear that we should not assume there is always a tag in the taglist.

Users probably don't notice this too much, since it's the JS thing that tries to find candidates, but we should fix it because crashes are ungood.

**Comment by mattiaverga** [comment] 2019-06-01 18:38
I don't think the problem is not having any build in taglist. The `KeyError: 0` seems to refer to the fact that `taglist` hasn't any `0` key, it's not an index error.

https://github.com/fedora-infra/bodhi/blob/4.0.2/bodhi/server/views/generic.py#L281:L291
I don't fully understand what the `response = koji.multiCall()` content is, but I can see a 500 Server error on bodhi if I query for latest candidates of a package with `testing=True`:
https://bodhi.fedoraproject.org/latest_candidates?package=kernel&testing=1

**Comment by mattiaverga** [comment] 2019-06-02 09:04
This is an example of a koji response that fires the crash:
```
[
  [
    []
  ],
  [
    []
  ],
  [
    [
      {
        "build_id": 1229284,
        "owner_name": "jforbes",
        "package_name": "kernel",
        "task_id": 33402445,
        "state": 1,
        "nvr": "kernel-4.20.15-200.fc29",
        "start_time": "2019-03-11 15:41:49.360165",
        "creation_event_id": 41010807,
        "creation_time": "2019-03-11 15:41:49.360165",
        "epoch": null,
        "tag_id": 3423,
        "completion_time": "2019-03-11 20:51:10.341605",
        "tag_name": "f29-updates-candidate",
        "version": "4.20.15",
        "volume_id": 1,
        "release": "200.fc29",
        "package_id": 8,
        "owner_id": 926,
        "id": 1229284,
        "volume_name": "prod",
        "name": "kernel"
      }
    ]
  ],
  [
    []
  ],
  [
    []
  ],
  [
    []
  ],
  [
    [
      {
        "build_id": 1228626,
        "owner_name": "jforbes",
        "package_name": "kernel",
        "task_id": 33384213,
        "state": 1,
        "nvr": "kernel-5.0.1-300.fc30",
        "start_time": "2019-03-11 04:09:32.333925",
        "creation_event_id": 40988486,
        "creation_time": "2019-03-11 04:09:32.333925",
        "epoch": null,
        "tag_id": 4375,
        "completion_time": "2019-03-11 09:41:36.357654",
        "tag_name": "f30-updates-candidate",
        "version": "5.0.1",
        "volume_id": 1,
        "release": "300.fc30",
        "package_id": 8,
        "owner_id": 926,
        "id": 1228626,
        "volume_name": "prod",
        "name": "kernel"
      }
    ]
  ],
  [
    []
  ],
  {
    "faultCode": 1000,
    "traceback": [
      "Traceback (most recent call last):\n",
      "  File \"/usr/share/koji-hub/kojixmlrpc.py\", line 332, in multiCall\n    result = self._dispatch(call['methodName'], call['params'])\n",
      "  File \"/usr/share/koji-hub/kojixmlrpc.py\", line 315, in _dispatch\n    ret = koji.util.call_with_argcheck(func, params, opts)\n",
      "  File \"/usr/lib/python2.7/site-packages/koji/util.py\", line 263, in call_with_argcheck\n    return func(*args, **kwargs)\n",
      "  File \"/usr/share/koji-hub/kojihub.py\", line 9772, in listTagged\n    tag = get_tag(tag, strict=True, event=event)['id']\n",
      "  File \"/usr/share/koji-hub/kojihub.py\", line 3085, in get_tag\n    raise koji.GenericError(\"Invalid tagInfo: %r\" % tagInfo)\n",
      "GenericError: Invalid tagInfo: 'f30-container-updates-candidate'\n"
    ],
    "faultString": "Invalid tagInfo: 'f30-container-updates-candidate'"
  },
  {
    "faultCode": 1000,
    "traceback": [
      "Traceback (most recent call last):\n",
      "  File \"/usr/share/koji-hub/kojixmlrpc.py\", line 332, in multiCall\n    result = self._dispatch(call['methodName'], call['params'])\n",
      "  File \"/usr/share/koji-hub/kojixmlrpc.py\", line 315, in _dispatch\n    ret = koji.util.call_with_argcheck(func, params, opts)\n",
      "  File \"/usr/lib/python2.7/site-packages/koji/util.py\", line 263, in call_with_argcheck\n    return func(*args, **kwargs)\n",
      "  File \"/usr/share/koji-hub/kojihub.py\", line 9772, in listTagged\n    tag = get_tag(tag, strict=True, event=event)['id']\n",
      "  File \"/usr/share/koji-hub/kojihub.py\", line 3085, in get_tag\n    raise koji.GenericError(\"Invalid tagInfo: %r\" % tagInfo)\n",
      "GenericError: Invalid tagInfo: 'f30-flatpak-updates-candidate'\n"
    ],
    "faultString": "Invalid tagInfo: 'f30-flatpak-updates-candidate'"
  },
  {
    "faultCode": 1000,
    "traceback": [
      "Traceback (most recent call last):\n",
      "  File \"/usr/share/koji-hub/kojixmlrpc.py\", line 332, in multiCall\n    result = self._dispatch(call['methodName'], call['params'])\n",
      "  File \"/usr/share/koji-hub/kojixmlrpc.py\", line 315, in _dispatch\n    ret = koji.util.call_with_argcheck(func, params, opts)\n",
      "  File \"/usr/lib/python2.7/site-packages/koji/util.py\", line 263, in call_with_argcheck\n    return func(*args, **kwargs)\n",
      "  File \"/usr/share/koji-hub/kojihub.py\", line 9772, in listTagged\n    tag = get_tag(tag, strict=True, event=event)['id']\n",
      "  File \"/usr/share/koji-hub/kojihub.py\", line 3085, in get_tag\n    raise koji.GenericError(\"Invalid tagInfo: %r\" % tagInfo)\n",
      "GenericError: Invalid tagInfo: 'f31-container-updates-candidate'\n"
    ],
    "faultString": "Invalid tagInfo: 'f31-container-updates-candidate'"
  }
]
```

**Comment by mattiaverga** [comment] 2019-06-02 09:16
`koji.listTagged` uses `strict=True` for searching the tag name and this behavior is not editable:
https://github.com/koji-project/koji/blob/2460a00117f8f7c9a64c96415cf638d9385a824b/hub/kojihub.py#L9775
That returns a dict instead of an empty list in case of the tag is not recognized. We could check `taglist` type in `response` or we could ask koji people to return the expected type from the function.

**Comment by mattiaverga** [comment] 2019-06-03 07:26
I have reported the unexpected koji behavior to upstream: https://pagure.io/koji/issue/1477

**Comment by AdamSaleh** [comment] 2019-11-04 07:57
@mattiaverga this issue seems to have been fixed some time ago by adding additional check: https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/views/generic.py#L319

**Comment by mattiaverga** [comment] 2019-11-04 17:03
@AdamSaleh good catch, a workaround was introduced in 1a48548d911566fb54a187f41bc74c61f4430572

**Comment by mattiaverga** [comment] 2020-03-21 14:41
we forgot to close this

**Closed as completed by mattiaverga** 2020-03-21 14:41 UTC
Labels: EasyFix, Critical, Buildroot Override, Crash
