### ISSUE TITLE
WebUI accepts same build listed twice, displays strangely in user profile but can't be fixed

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#1251] opened 2017-01-26 10:18 UTC
I was trying to submit a single update with both `fedfind-3.4.0-1.fc24` and `fedfind-3.4.0-1.fc25` listed (which results in Bodhi cleverly splitting it up into two otherwise-identical updates, one for F24, one for F25). But by mistake I just listed `fedfind-3.4.0-1.fc24` twice instead. The result was interesting. Bodhi accepted it without complaint, and I get [an update](https://bodhi.fedoraproject.org/updates/FEDORA-2017-eb562ccca1) that mostly looks OK. However, in my user profile page, it shows up listed as 'fedfind-3.4.0-1.fc24 fedfind-3.4.0-1.fc24' - see screenshot. I can't see any way to fix it, as the build isn't listed twice when I edit the update. I also don't know if there might be any other hidden consequences of this.

![Screenshot of the user profile](https://cloud.githubusercontent.com/assets/916551/22327752/1181f844-e3b9-11e6-8650-418e134f7a2a.png)

**Comment by jeremycline** [comment] 2017-01-26 15:41
@AdamWill If it makes you feel better, I don't think you accidentally listed the fc24 build twice. There's currently a hotpatch in production that introduced a regression (which I found and fixed in https://github.com/fedora-infra/bodhi/pull/1232/commits/9ac5f8436ed0845e12ff84066298e03367e28311) in accepting multiple updates at once. The version in production enters a loop of builds, but queries the database using a variable defined outside the loop. The result is it only ever comes up with one build.

**Comment by jeremycline** [comment] 2017-01-26 15:55
Glancing at the [offending function](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/services/updates.py#L332) it's hard to tell how bad this is. I _think_ duplicate builds are being handed to the [Update model's new method](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/models/models.py#L710) and at least being used to set the ``requirements`` field, but I'm not sure what exactly that's used for since the model is completely undocumented. Someone with more intimate knowledge of Bodhi's modeling should probably set the priority on this.

**Comment by mbooth101** [comment] 2017-01-27 15:08
I have a similar problem with https://bodhi.fedoraproject.org/updates/FEDORA-2017-e86e3c8e50

Only I actually tried to create update with three different packages (all for F25) and the result is an update with only first package I added, but that package is shown three times in the same view as @AdamWill has screenshotted: https://bodhi.fedoraproject.org/updates/?user=mbooth

**Comment by AdamWill** [comment] 2017-01-27 23:24
yeah, I talked to @bowlofeggs today and he said he thinks I probably did create the update correctly, but Bodhi has a known bug ATM that causes this result.

**Comment by remicollet** [comment] 2017-01-30 10:26
same than #1253 and perhaps related to #1255

**Comment by siwinski** [comment] 2017-01-30 17:57
I am having the same issue.  I tried to create an update of a new library stack that has 13 packages and 3 dists (f25, f24, epel7) and only 1 update with 1 package was created: https://bodhi.fedoraproject.org/updates/FEDORA-2017-70b54af759

**Comment by igor-raits** [comment] 2017-01-30 17:57
I think I have same problem on #1256 as well...

**Comment by siwinski** [comment] 2017-01-30 18:01
"Interesting" bugzilla update also:

https://bugzilla.redhat.com/show_bug.cgi?id=1414844#c5

> Fedora Update System 2017-01-30 12:50:23 EST
>
> php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 php-react-0.4.2-2.fc24 has been submitted as an update to Fedora 24. https://bodhi.fedoraproject.org/updates/FEDORA-2017-70b54af759

**Comment by jeremycline** [comment] 2017-01-30 18:34
I believe all the problems mentioned here should be fixed (with the possible exception of #1255 - I'll investigate that now) when https://github.com/fedora-infra/bodhi/pull/1232 is tagged into a release and pushed to production. @bowlofeggs is currently traveling so it may be a few days before that happens.

**Comment by bowlofeggs** [comment] 2017-02-01 23:05
I talked with @jeremycline today and it sounds like he built/released a new Bodhi build to fix this, and @nirik installed it on production. That should suppress the issue where builds with different releases get counted as the same build multiple times on one release.

I believe we can close this issue as a result. Please do comment here if you disagree!

**Closed as completed by bowlofeggs** 2017-02-01 23:05 UTC
Labels: High priority

**Comment by siwinski** [comment] 2017-02-02 18:23
Sorry for the late reply... things look fixed from my end as I was able to submit my multi-dist multi-pkg updates 😄    THANKS!

- https://bodhi.fedoraproject.org/updates/FEDORA-2017-01c3948081
- https://bodhi.fedoraproject.org/updates/FEDORA-2017-70b54af759
- https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2017-7258a839b5

**Comment by bowlofeggs** [comment] 2017-02-02 18:56
On Thu, 2017-02-02 at 10:23 -0800, Shawn Iwinski wrote:
> things look fixed from my end as I was able to submit my multi-dist
> multi-pkg updates 😄

Fantastic, thanks Shawn!
