### ISSUE TITLE
Search does not work?

### ISSUE THREAD

**Issue by voxik** [fedora-infra/bodhi#4041] opened 2020-05-27 14:09 UTC
Trying to access update information about rubygem-net-ssh [[1]], it always files with "504 Gateway Time-out". I am not sure how to access this information via different means :(

[1]: https://bodhi.fedoraproject.org/updates/?packages=rubygem-net-ssh

**Comment by cverna** [comment] 2020-05-27 14:18
There is an outage going on (https://status.fedoraproject.org/), still not sure what is the cause of it yet.

**Comment by cverna** [comment] 2020-05-29 13:13
This should be resolved now, closing it

**Closed as completed by cverna** 2020-05-29 13:13 UTC
