### ISSUE TITLE
Not getting reminder emails

### ISSUE THREAD

**Issue by opoplawski** [fedora-infra/bodhi#517] opened 2015-09-08 14:56 UTC
I no longer appear to be getting emails saying that an update has waiting enough time and can be pushed to stable.

**Comment by ralphbean** [comment] 2015-09-08 15:04
Thanks @opoplawski.  This is a duplicate of #298.

**Comment by opoplawski** [comment] 2015-09-08 15:08
Ah, didn't find the right search term...

**Closed** 2015-09-08 15:08 UTC
