### ISSUE TITLE
Can't create an update with the same build as was in an unpushed update

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#1809] opened 2017-09-15 13:42 UTC
If you unpush an update with some build, you can't create a new update with the same build NVR. That makes it problematic for certain use cases, e.g. like merging two updates together.

See this discussion for further details:
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/JCOLM4HHMSY24J734KASUT2ZIUNIS3AW/

**Comment by bowlofeggs** [comment] 2017-09-18 02:40
This is a pain point I've hit a few times before too.

**Comment by QuLogic** [comment] 2019-02-17 05:52
Still an issue, but this is actually a duplicate of #842.

**Comment by bowlofeggs** [comment] 2019-02-18 16:15
I agree that #842 would help solve this problem, but I'm not sure it's exactly a duplicate of this due to the unpushed nature here (the other ticket is about merging two active updates into one).

**Comment by hroncok** [comment] 2020-02-06 10:31
Can this or https://github.com/fedora-infra/bodhi/issues/842 be prioritized please? Handling subsequent updates that need to be manually synchronized is a huge PITA:

https://bodhi.fedoraproject.org/updates/FEDORA-2020-5d6c8b0c64

**Comment by cverna** [comment] 2020-02-06 13:53
Currently we don't have much time to work on Bodhi with the FAS rewrite going on, the work to automate the changelog generation and preparation for the data center move.

I can tag this as High Priority but we have quite a few of these :(. 

If anyone is willing to try to implement this, I ll be happy to help answering question and review the code tho.

**Closed as completed** 2020-09-26 09:54 UTC
Labels: RFE
