### ISSUE TITLE
Missing "Push to stable" button

### ISSUE THREAD

**Issue by zdohnal** [fedora-infra/bodhi#1952] opened 2017-10-30 09:35 UTC
Hi,
my update automatically requested "batched" state, but there should be button for "Push to stable", which is missing. If I understood it correctly, updates automatically requests "batched", but update's creator should have option to manually request "push to stable" state? But I cannot find any way to do it now.

**Comment by puiterwijk** [comment] 2017-10-30 09:36
Could you please provide the link to the update?

**Comment by zdohnal** [comment] 2017-10-30 09:37
Hi, sure, here it is https://bodhi.fedoraproject.org/updates/FEDORA-2017-da1e383f18 .

**Comment by bowlofeggs** [comment] 2017-10-30 14:56
It's not immediately obvious to me what the problem is, but I'll take a closer look soon. In the meantime, you can use the ```bodhi >= 2``` CLI to do this as a workaround:

```
$ bodhi updates request FEDORA-2017-da1e383f18 stable
```

I believe it's possible with the bodhi-0.9 CLI as well, but I'm not familar enough with it to write the command ☺

**Comment by zdohnal** [comment] 2017-10-30 14:58
Thank you, it worked :)

**Comment by bowlofeggs** [comment] 2017-10-31 21:54
For some reason, I had thought that we had already fixed and released #1907, but I just realized that it was not part of the 3.0.0 release. Thus, I believe this issue is a duplicate of that one, which will be fixed in the upcoming 3.1.0 release.

**Closed as completed by bowlofeggs** 2017-10-31 21:54 UTC
Labels: High priority, reliability, WebUI

**Comment by zdohnal** [comment] 2017-11-01 07:13
Ok, thank you Randy. I have Fedora 26 with bodhi-client-2.8.1-1.fc26 - when will 3.0.0/3.0.1 arrive to f26?

**Comment by bowlofeggs** [comment] 2017-11-01 15:21
Hello @zdohnal!

I don't plan to release Bodhi 3 on Fedora < 28 because it is not backwards compatible. However, this issue is a web UI issue and not a CLI issue, so it will be fixed for you when we deploy 3.1.0 to production. I anticipate that happening sometime in the next week or two.

**Comment by bowlofeggs** [comment] 2017-11-08 18:55
This patch is included in the bodhi-3.1.0-0.1.beta, which is deployed to [staging](https://bodhi.stg.fedoraproject.org/) and is also available via [Copr](https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release/).
