### ISSUE TITLE
Bodhi can change state of RHEL bugs

### ISSUE THREAD

**Issue by yarda** [fedora-infra/bodhi#1735] opened 2017-08-09 08:49 UTC
This is Fedora/RHEL specific issue, originally reported as [1] and after request in the original ticket taken upstream.

The problem is that if Fedora update has associated bug which is RHEL bug, Bodhi can change it's state, which I think it shouldn't do. I think there should be some filter for bugzilla product, because such things can happen.

For me it happen the following way:
I had "related: rhbz#" in change log which pointed to the RHEL bug from where the patch were cherry picked. This went through the "fedpkg log" and "fedpkg commit" to the commit message and the bug number were reused by the "fedpkg update" and went into Bodhi which later manipulated state of the RHEL bug. I.e. RHEL-7 bug which which was in the VERIFIED state was accidentally switched to the ON_QA state by Fedora Update System [2].

Well, I know, I should clone the bug to Fedora or remove it from Bodhi or set the update not to close the bug, but such things can happen and the infrastructure should handle it correctly. Also IIRC it worked the requested way sometime in the past (maybe Bodhi 1).

[1] https://pagure.io/fedora-infrastructure/issue/6191
[2] https://bugzilla.redhat.com/show_bug.cgi?id=890585

**Comment by bowlofeggs** [comment] 2017-08-11 21:09
Thanks for the report! This is a duplicate of https://github.com/fedora-infra/bodhi/issues/1043 so I suggest subscribing there.

**Closed as completed by bowlofeggs** 2017-08-11 21:09 UTC

**Comment by pcahyna** [comment] 2017-08-21 10:23
For me it happened when I cloned a Fedora bug to RHEL and Bodhi kept changing the status of the RHEL one: https://github.com/fedora-infra/bodhi/issues/1043#issuecomment-323702481
