### ISSUE TITLE
Bodhi badly remove buildroot overrides.

### ISSUE THREAD

**Issue by remicollet** [fedora-infra/bodhi#1127] opened 2016-11-22 16:11 UTC
I had a buildroot override active for `php-phpunit-PHPUnit-5.6.5-1.fc25`

At some point I added this build to an update. (the update already existed and contained an earlier build for this package, but that shouldn't matter)

After that, Bodhi untagged the override.

You can see this from the build's tag history (only the relevant parts kept) :

```
$ koji list-tag-history  --build=php-phpunit-PHPUnit-5.6.5-1.fc25
Tue Nov 22 13:10:38 2016: php-phpunit-PHPUnit-5.6.5-1.fc25 tagged into f25-override by bodhi
Tue Nov 22 13:43:57 2016: php-phpunit-PHPUnit-5.6.5-1.fc25 untagged from f25-override by bodhi
```

Looking at the date, it clearly got untagged when I added it to the update:

https://bodhi.fedoraproject.org/updates/FEDORA-2016-968d9d201e#comment-524859

Adding a build to an update shouldn't untag an override.

**Comment by bowlofeggs** [comment] 2016-11-26 03:55
This sounds like a duplicate of https://github.com/fedora-infra/bodhi/issues/798. Please let me know if you think it's a separate issue!

**Closed as completed by bowlofeggs** 2016-11-26 03:55 UTC
