### ISSUE TITLE
Bodhi2 sucks

### ISSUE THREAD

**Issue by leigh123linux** [fedora-infra/bodhi#220] opened 2015-08-20 09:15 UTC
Issues so far.

1. No button to push to stable (after seven day limit).
2. unable to create epel7 updates

**Comment by nullr0ute** [comment] 2015-08-20 10:28
The title is not useful. Also what you have above is two problems so please report them as such with proper details and feedback including NVRs.

**Comment by leigh123linux** [comment] 2015-08-20 10:42
The epel7 issue is reported here

https://github.com/fedora-infra/bodhi/issues/218

I can't submit tint2-0.12.2-1.el7

**Comment by nullr0ute** [comment] 2015-08-20 10:51
have you tried on using "fedpkg update" with at least python-fedora-0.5.5-1 and bodhi-client-0.9.12.2-3

**Comment by leigh123linux** [comment] 2015-08-20 11:25
Yes

```
$ fedpkg switch-branch epel7 
Switched to branch 'epel7'
[leigh@pc-main tint2]$ fedpkg update
/usr/lib/python2.7/site-packages/fedpkg/cli.py:169: DeprecationWarning: Commands._hash_file is deprecated and will be removed eventually.
    Please use Commands.lookasidecache.hash_file instead.
  hash = self.cmd._hash_file('bodhi.template', 'sha1')
Creating a new update for  tint2-0.12.2-1.el7 
Password for leigh123linux: 
Creating a new update for  tint2-0.12.2-1.el7 
ServerError(https://bodhi.fedoraproject.org/updates/, 500, Error returned from json module while processing https://bodhi.fedoraproject.org/updates/: Expecting value: line 1 column 1 (char 0))
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 225, in main
    data = bodhi.save(**update_args)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 96, in wrapper
    result = method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 170, in save
    data=kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 374, in send_request
    {'url': to_bytes(method), 'err': to_bytes(e)})
ServerError: ServerError(https://bodhi.fedoraproject.org/updates/, 500, Error returned from json module while processing https://bodhi.fedoraproject.org/updates/: Expecting value: line 1 column 1 (char 0))
Could not generate update request: Command 'bodhi --new --release epel7 --file bodhi.template tint2-0.12.2-1.el7 --username leigh123linux' returned non-zero exit status 255
```

and also bumped the release and did a new build in case the old build was blocking it 

```
bodhi --new --release epel7 --file bodhi.template tint2-0.12.2-2.el7 --username leigh123linux
Creating a new update for  tint2-0.12.2-2.el7 
Password for leigh123linux: 
Creating a new update for  tint2-0.12.2-2.el7 
ServerError(https://bodhi.fedoraproject.org/updates/, 500, Error returned from json module while processing https://bodhi.fedoraproject.org/updates/: Expecting value: line 1 column 1 (char 0))
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 225, in main
    data = bodhi.save(**update_args)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 96, in wrapper
    result = method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 170, in save
    data=kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 374, in send_request
    {'url': to_bytes(method), 'err': to_bytes(e)})
ServerError: ServerError(https://bodhi.fedoraproject.org/updates/, 500, Error returned from json module while processing https://bodhi.fedoraproject.org/updates/: Expecting value: line 1 column 1 (char 0))
```

**Comment by leigh123linux** [comment] 2015-08-20 11:26
```
$ rpm -q python-fedora bodhi-client
python-fedora-0.5.5-1.fc22.noarch
bodhi-client-0.9.12.2-3.fc22.noarch
```

**Comment by lmacken** [comment] 2015-08-20 13:28
1 is a duplicate of #233 
2 is a duplicate of #218, and is now resolved.

**Closed by lmacken** 2015-08-20 13:28 UTC
