### ISSUE TITLE
multi-type update (e.g. newpackage + bugfix)

### ISSUE THREAD

**Issue by igor-raits** [fedora-infra/bodhi#859] opened 2016-07-07 18:09 UTC
For example, we have missing `Requires` in `python-aiohttp` with package which doesn't exist (`python-multidict`).

I package `python-multidict`, pass review, build in koji. Adding Requires to aiohttp. And now comes interesting thing, how should I handle update? For multidict update type is newpackage, but for aiohttp it is bugfix, but those updates are in dependency chain.

Would be great to implement dependencies between updates or choice of update type for each build in update.

**Comment by pypingou** [comment] 2016-07-07 18:10
I remember there was a discussion at one point about dependencies between updates, I guess this relates to that as well

**Comment by ryanlerch** [comment] 2017-06-30 02:16
Duplicate of #224

**Closed as completed by ryanlerch** 2017-06-30 02:16 UTC
Labels: RFE
