### ISSUE TITLE
Updates created by bodhi cli don't close attached bugzillas even with --close-bugs option added

### ISSUE THREAD

**Issue by zdohnal** [fedora-infra/bodhi#2162] opened 2018-02-20 12:48 UTC
Hi,

I'm creating updates for my component by 'bodhi updates' cli command with '--bugs bugzilla_num --close-bugs' options, but update doesn't close attached bugzilla. Would you mind looking into it?

**Comment by bowlofeggs** [comment] 2018-02-20 16:12
This is a duplicate of #1818. There's good news though, because @cverna sent a patch at #2149!

**Closed as completed by bowlofeggs** 2018-02-20 16:12 UTC

**Comment by zdohnal** [comment] 2018-02-20 16:20
That's interesting - I thought it worked around the time when  #1818 was created... anyway, sorry for duplicate.

**Comment by bowlofeggs** [comment] 2018-02-20 16:47
@zdohnal no problem at all, thanks for the report!
