### ISSUE TITLE
Cannot remove builds in the new UI from

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#3651] opened 2019-10-25 07:14 UTC
When creating a new update and selecting the side tag option to populate the build list, the UI does not let me remove builds or change my choice to use a side tag.

I think the user should be able to clear the list of builds in order to restart from scratch.

**Comment by ryanlerch** [comment] 2019-10-28 02:23
#3620 covers the not being able to go back to normal builds mode, but not sure how common this will be in actual use to be honest.

WRT removing / editing builds of a side tag, this is not possible really. there is the option to load new builds from a sidetag, but manual editing is not really a thing with sidetags, right? you just get the builds in the tag. on koji.

**Comment by ryanlerch** [comment] 2019-10-28 09:32
marking this as a dupe of #3620

**Closed as completed by ryanlerch** 2019-10-28 09:32 UTC
Labels: WebUI
