### ISSUE TITLE
When an update is locked, feedback appears to be ignored but is apparently cached, which leads to multiple submissions from the same user

### ISSUE THREAD

**Issue by dhgutteridge** [fedora-infra/bodhi#717] opened 2015-11-29 02:48 UTC
It appears when an update is locked, the form will allow users to submit feedback, however, the submit button just "spins" at the bottom, and after a while returns to the static "submit" button without any sign of anything happening. There's no indication the feedback was recorded/accepted. This causes users (myself included, until I figured this out just now) to try and submit feedback multiple times, since the functionality appears to be silently failing. Then when the update unlocks, it accepts all the form submissions, so the same user's comment is recorded however many times they tried to submit. It's smart enough not to count karma more than once from the same submitter, but not smart enough to pop up a warning saying "the package is locked, receipt of feedback will be delayed" or identify multiple form submissions with identical content.

**Comment by dhgutteridge** [comment] 2015-12-06 07:27
I'm no longer sure this is due to updates being in a locked state. I've now successfully submitted feedback immediately while packages are locked. Perhaps there's a different cause for this, or perhaps it happens during a particular sub-state of being locked. (I've still encountered this issue within the last day, so I doubt anything's been fixed in this regard.)

**Comment by lmacken** [comment] 2015-12-07 17:52
Yeah, being locked shouldn't affect the comments/karma at all. Do you have an example of an update that you're seeing this behavior with?

**Comment by dhgutteridge** [comment] 2015-12-07 20:46
The latest example it happened to me with is this one: https://bodhi.fedoraproject.org/updates/FEDORA-2015-f26dec73e9. It stalled until the update was pushed to testing, then both my button clicks were taken as feedback. (There are more where this came from but they're older. I've seen it happen to other people as well.)

**Comment by dhgutteridge** [comment] 2015-12-14 13:37
"A Tale of Two Updates":

https://bodhi.fedoraproject.org/updates/FEDORA-2015-641840267e: Submitted feedback at 3:10am. No sign anything happened. Manually refreshed page, no sign of feedback being taken. Received email at 5:28am showing the feedback was recorded then.

https://bodhi.fedoraproject.org/updates/FEDORA-2015-9e822a49a1: Submitted feedback at 3:14am and was processed successfully right away. Received email at 3:14am.

Both updates were marked locked at the time. The one with the delayed feedback shows it was pushed to stable three minutes before it finally recorded what I'd posted.

**Comment by dhgutteridge** [comment] 2016-11-16 19:18
I still encounter this issue from time to time, but I haven't been able to narrow down why it's happening.

**Comment by dhgutteridge** [comment] 2017-01-09 19:09
This issue recurred for me yesterday, with [https://bodhi.fedoraproject.org/updates/FEDORA-2017-1e3e237ac8](url). I tried to submit feedback, but Bodhi showed no sign it had been received, so I tried resubmitting twice. Nothing happened until after the package was pushed to stable, then all my attempts were recorded (with the times of submission being incorrect -- showing after the package was pushed to stable rather than an hour before).

**Comment by dhgutteridge** [comment] 2017-02-02 21:30
I've found this is 100% reproducible: a package has to be in the process of being pushed to stable and in a "locked" state, at which point, Bodhi doesn't register any further karma submissions until after the package lands in stable. Then it records the submissions. I just confirmed this with [https://bodhi.fedoraproject.org/updates/FEDORA-2017-921eec0341](url), where I deliberately waited until it was in that state before commenting.

**Comment by jankratochvil** [comment] 2017-03-30 20:16
I see the same case now with: https://bodhi.fedoraproject.org/updates/FEDORA-2017-0ffb8246fa
I have already clicked it several times, I still see no new comment there.  Now nirik told me and I see there is:
_Locked: This update is currently locked since 2017-03-30 19:35:47 (UTC) and cannot be modified._

**Comment by bowlofeggs** [comment] 2017-05-19 14:36
I have witnessed this problem on production, but strangely I am unable to reproduce it in my development environment. Unfortunately, due to https://github.com/fedora-infra/bodhi/issues/1318 I am unable to log in to staging to test it there. Once #1318 is fixed, I hope that it is reproducible in staging so I can debug it there.

**Comment by dustymabe** [comment] 2017-05-31 20:23
I saw this today when trying to edit https://bodhi.fedoraproject.org/updates/FEDORA-2017-2c70da042c. There will probably be like 20 comments from me when it finally get's unlocked.

**Comment by dustymabe** [comment] 2017-05-31 20:30
@bowlofeggs can you update the code to  populate the comment text box with some text that says

*this update is currently locked, there is a known bug [link] where submitting feedback while the update is locked can possibly not show up immediately . Submit your feedback once and trust that it will make it through once the update is unlocked*

**Comment by bowlofeggs** [comment] 2017-05-31 21:08
We could do something like that, but this issue may be specific to Fedora's deployment in some way as I am not able to reproduce it in the dev environment.

**Comment by dustymabe** [comment] 2017-05-31 21:23
in that case we could make it generic `DEFAULT_COMMENT_BOX_TEXT=""` and then our particular deployment could have that variable configured

**Comment by bowlofeggs** [comment] 2017-07-03 18:16
One problem that will arise if we fix this is that negative karma won't be counted if it is accepted. Imagine that an update is being mashed and then 10 people -1 it. It will be confusing when the -7 update goes to stable since Bodhi accepted the 10 -1's before marking it as stable.

@nirik suggested accepting comments into a queue so that the UI at least responds to the comments, but also indicates that they aren't going to count against the current mash operation. We could display the comments in grey or something to make this clear. We could also make sure that the Bodhi comment that says the update is pushed goes in before the comments do so they appear after the state change for future historical record.

**Comment by kparal** [comment] 2017-07-04 12:33
> One problem that will arise if we fix this is that negative karma won't be counted if it is accepted. Imagine that an update is being mashed and then 10 people -1 it. It will be confusing when the -7 update goes to stable since Bodhi accepted the 10 -1's before marking it as stable.

I don't think it will be confusing if you add a note to the comments section that this update is being processed and karma votes have no further effect. Something like this:

> user1: comment, +1
> user2: comment, +1
> This update has been submitted for stable by $maintainer.
> user3: comment, +1
> This update is now being processed for stable and additional karma votes have no further effect.
> user4: comment, -1
> user5: comment, -1
> This update has been pushed to stable.

**Closed** 2017-12-11 18:49 UTC

**Comment by bowlofeggs** [comment] 2017-12-19 19:21
The patch for this will be included in the upcoming 3.2.0 release:

https://github.com/fedora-infra/bodhi/pull/2092
